window.equipment.feet = {
  "20th anniversary boots": {
    "image_url": "https://oldschool.runescape.wiki/images/e/e0/20th_anniversary_boots.png?3e370",
    "wiki_url": "https://oldschool.runescape.wiki/w/20th_anniversary_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Adamant boots": {
    "image_url": "https://oldschool.runescape.wiki/images/e/e5/Adamant_boots.png?b714a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Adamant_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-3",
    "ranged_atk": "-1",
    "stab_def": "+10",
    "slash_def": "+11",
    "crush_def": "+12",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+1",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ancient d'hide boots": {
    "image_url": "https://oldschool.runescape.wiki/images/e/e0/Ancient_d%27hide_boots.png?0b6b6",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ancient_d%27hide_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-10",
    "ranged_atk": "+7",
    "stab_def": "+4",
    "slash_def": "+4",
    "crush_def": "+4",
    "magic_def": "+4",
    "ranged_def": "+4",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+1"
  },
  "Angler boots": {
    "image_url": "https://oldschool.runescape.wiki/images/7/76/Angler_boots.png?f0f17",
    "wiki_url": "https://oldschool.runescape.wiki/w/Angler_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ankou socks": {
    "image_url": "https://oldschool.runescape.wiki/images/a/a7/Ankou_socks.png?cbe92",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ankou_socks",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Antisanta boots": {
    "image_url": "https://oldschool.runescape.wiki/images/2/21/Antisanta_boots.png?38864",
    "wiki_url": "https://oldschool.runescape.wiki/w/Antisanta_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Armadyl d'hide boots": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b0/Armadyl_d%27hide_boots.png?e56f0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Armadyl_d%27hide_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-10",
    "ranged_atk": "+7",
    "stab_def": "+4",
    "slash_def": "+4",
    "crush_def": "+4",
    "magic_def": "+4",
    "ranged_def": "+4",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+1"
  },
  "Bandos boots": {
    "image_url": "https://oldschool.runescape.wiki/images/0/0c/Bandos_boots.png?f928c",
    "wiki_url": "https://oldschool.runescape.wiki/w/Bandos_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-5",
    "ranged_atk": "-3",
    "stab_def": "+17",
    "slash_def": "+18",
    "crush_def": "+19",
    "magic_def": "+0",
    "ranged_def": "+15",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+1"
  },
  "Bandos d'hide boots": {
    "image_url": "https://oldschool.runescape.wiki/images/d/da/Bandos_d%27hide_boots.png?f928c",
    "wiki_url": "https://oldschool.runescape.wiki/w/Bandos_d%27hide_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-10",
    "ranged_atk": "+7",
    "stab_def": "+4",
    "slash_def": "+4",
    "crush_def": "+4",
    "magic_def": "+4",
    "ranged_def": "+4",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+1"
  },
  "Bear feet": {
    "image_url": "https://oldschool.runescape.wiki/images/2/26/Bear_feet.png?0b6b6",
    "wiki_url": "https://oldschool.runescape.wiki/w/Bear_feet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Beekeeper's boots": {
    "image_url": "https://oldschool.runescape.wiki/images/7/7f/Beekeeper%27s_boots.png?356fd",
    "wiki_url": "https://oldschool.runescape.wiki/w/Beekeeper%27s_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Black boots": {
    "image_url": "https://oldschool.runescape.wiki/images/1/1f/Black_boots.png?356fd",
    "wiki_url": "https://oldschool.runescape.wiki/w/Black_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-3",
    "ranged_atk": "-1",
    "stab_def": "+7",
    "slash_def": "+8",
    "crush_def": "+9",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Bloodbark boots": {
    "image_url": "https://oldschool.runescape.wiki/images/4/43/Bloodbark_boots.png?d13d3",
    "wiki_url": "https://oldschool.runescape.wiki/w/Bloodbark_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+4",
    "ranged_atk": "+0",
    "stab_def": "+5",
    "slash_def": "+4",
    "crush_def": "+6",
    "magic_def": "+5",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Blue boots": {
    "image_url": "https://oldschool.runescape.wiki/images/9/9e/Blue_boots.png?3b913",
    "wiki_url": "https://oldschool.runescape.wiki/w/Blue_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Boots of brimstone": {
    "image_url": "https://oldschool.runescape.wiki/images/7/71/Boots_of_brimstone.png?9ae5a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Boots_of_brimstone",
    "stab_atk": "+3",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+3",
    "ranged_atk": "+5",
    "stab_def": "+10",
    "slash_def": "+10",
    "crush_def": "+10",
    "magic_def": "+5",
    "ranged_def": "+5",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Boots of darkness": {
    "image_url": "https://oldschool.runescape.wiki/images/f/f0/Boots_of_darkness.png?9ae5a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Boots_of_darkness",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+3",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+3",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Boots of lightness#Worn": {
    "image_url": "https://oldschool.runescape.wiki/images/f/f4/Boots_of_lightness.png?9ae5a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Boots_of_lightness#Worn",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+1",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Boots of stone": {
    "image_url": "https://oldschool.runescape.wiki/images/c/cf/Boots_of_stone.png?3d026",
    "wiki_url": "https://oldschool.runescape.wiki/w/Boots_of_stone",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+1",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Bronze boots": {
    "image_url": "https://oldschool.runescape.wiki/images/5/5e/Bronze_boots.png?05d25",
    "wiki_url": "https://oldschool.runescape.wiki/w/Bronze_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-3",
    "ranged_atk": "-1",
    "stab_def": "+1",
    "slash_def": "+2",
    "crush_def": "+3",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Builder's boots": {
    "image_url": "https://oldschool.runescape.wiki/images/2/22/Builder%27s_boots.png?c50c3",
    "wiki_url": "https://oldschool.runescape.wiki/w/Builder%27s_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Bunny feet": {
    "image_url": "https://oldschool.runescape.wiki/images/3/3b/Bunny_feet.png?acbdf",
    "wiki_url": "https://oldschool.runescape.wiki/w/Bunny_feet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Carpenter's boots": {
    "image_url": "https://oldschool.runescape.wiki/images/c/cc/Carpenter%27s_boots.png?3c432",
    "wiki_url": "https://oldschool.runescape.wiki/w/Carpenter%27s_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Chicken feet": {
    "image_url": "https://oldschool.runescape.wiki/images/0/0e/Chicken_feet.png?bcc94",
    "wiki_url": "https://oldschool.runescape.wiki/w/Chicken_feet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Citizen shoes": {
    "image_url": "https://oldschool.runescape.wiki/images/0/09/Citizen_shoes.png?98f30",
    "wiki_url": "https://oldschool.runescape.wiki/w/Citizen_shoes",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+2",
    "crush_def": "+2",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Climbing boots": {
    "image_url": "https://oldschool.runescape.wiki/images/a/a7/Climbing_boots.png?4d516",
    "wiki_url": "https://oldschool.runescape.wiki/w/Climbing_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+2",
    "crush_def": "+2",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+2",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Climbing boots (Last Man Standing)": {
    "image_url": "https://oldschool.runescape.wiki/images/a/ab/Climbing_boots_%28Last_Man_Standing%29.png?09bb0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Climbing_boots_(Last_Man_Standing)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+2",
    "crush_def": "+2",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+2",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Climbing boots (g)": {
    "image_url": "https://oldschool.runescape.wiki/images/7/71/Climbing_boots_%28g%29.png?09bb0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Climbing_boots_(g)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+2",
    "crush_def": "+2",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+2",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Clown shoes#During_event": {
    "image_url": "https://oldschool.runescape.wiki/images/a/a3/Clown_shoes.png?4d516",
    "wiki_url": "https://oldschool.runescape.wiki/w/Clown_shoes#During_event",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Clown shoes#Reward": {
    "image_url": "https://oldschool.runescape.wiki/images/a/a3/Clown_shoes.png?4d516",
    "wiki_url": "https://oldschool.runescape.wiki/w/Clown_shoes#Reward",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Clue hunter boots": {
    "image_url": "https://oldschool.runescape.wiki/images/7/72/Clue_hunter_boots.png?09bb0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Clue_hunter_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Cow shoes": {
    "image_url": "https://oldschool.runescape.wiki/images/c/c7/Cow_shoes.png?720eb",
    "wiki_url": "https://oldschool.runescape.wiki/w/Cow_shoes",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Cream boots": {
    "image_url": "https://oldschool.runescape.wiki/images/f/f8/Cream_boots.png?5352a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Cream_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Dark flippers": {
    "image_url": "https://oldschool.runescape.wiki/images/2/21/Dark_flippers.png?4806b",
    "wiki_url": "https://oldschool.runescape.wiki/w/Dark_flippers",
    "stab_atk": "-2",
    "slash_atk": "-2",
    "crush_atk": "-2",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Dark tuxedo shoes": {
    "image_url": "https://oldschool.runescape.wiki/images/0/07/Dark_tuxedo_shoes.png?3a184",
    "wiki_url": "https://oldschool.runescape.wiki/w/Dark_tuxedo_shoes",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Decorative boots (gold)#Broken": {
    "image_url": "https://oldschool.runescape.wiki/images/5/5f/Decorative_boots_%28broken%29_%28gold%29.png?090e3",
    "wiki_url": "https://oldschool.runescape.wiki/w/Decorative_boots_(gold)#Broken",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-3",
    "ranged_atk": "-1",
    "stab_def": "+10",
    "slash_def": "+11",
    "crush_def": "+12",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+1",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Decorative boots (gold)#Locked": {
    "image_url": "https://oldschool.runescape.wiki/images/6/62/Decorative_boots_%28l%29_%28gold%29.png?6b57c",
    "wiki_url": "https://oldschool.runescape.wiki/w/Decorative_boots_(gold)#Locked",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-3",
    "ranged_atk": "-1",
    "stab_def": "+10",
    "slash_def": "+11",
    "crush_def": "+12",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+1",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Decorative boots (gold)#Normal": {
    "image_url": "https://oldschool.runescape.wiki/images/9/99/Decorative_boots_%28gold%29.png?1a603",
    "wiki_url": "https://oldschool.runescape.wiki/w/Decorative_boots_(gold)#Normal",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-3",
    "ranged_atk": "-1",
    "stab_def": "+10",
    "slash_def": "+11",
    "crush_def": "+12",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+1",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Decorative boots (red)": {
    "image_url": "https://oldschool.runescape.wiki/images/e/e2/Decorative_boots_%28red%29.png?090e3",
    "wiki_url": "https://oldschool.runescape.wiki/w/Decorative_boots_(red)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-3",
    "ranged_atk": "-1",
    "stab_def": "+5",
    "slash_def": "+6",
    "crush_def": "+7",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Decorative boots (white)": {
    "image_url": "https://oldschool.runescape.wiki/images/0/05/Decorative_boots_%28white%29.png?3043c",
    "wiki_url": "https://oldschool.runescape.wiki/w/Decorative_boots_(white)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-3",
    "ranged_atk": "-1",
    "stab_def": "+8",
    "slash_def": "+9",
    "crush_def": "+10",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Demon feet": {
    "image_url": "https://oldschool.runescape.wiki/images/7/7d/Demon_feet.png?3043c",
    "wiki_url": "https://oldschool.runescape.wiki/w/Demon_feet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Desert boots": {
    "image_url": "https://oldschool.runescape.wiki/images/4/45/Desert_boots.png?6b57c",
    "wiki_url": "https://oldschool.runescape.wiki/w/Desert_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Devout boots": {
    "image_url": "https://oldschool.runescape.wiki/images/0/0a/Devout_boots.png?3043c",
    "wiki_url": "https://oldschool.runescape.wiki/w/Devout_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+5"
  },
  "Dragon boots": {
    "image_url": "https://oldschool.runescape.wiki/images/d/d7/Dragon_boots.png?c85b3",
    "wiki_url": "https://oldschool.runescape.wiki/w/Dragon_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-3",
    "ranged_atk": "-1",
    "stab_def": "+16",
    "slash_def": "+17",
    "crush_def": "+18",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+4",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Dragon boots (g)": {
    "image_url": "https://oldschool.runescape.wiki/images/c/ce/Dragon_boots_%28g%29.png?c85b3",
    "wiki_url": "https://oldschool.runescape.wiki/w/Dragon_boots_(g)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-3",
    "ranged_atk": "-1",
    "stab_def": "+16",
    "slash_def": "+17",
    "crush_def": "+18",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+4",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Dragonstone boots": {
    "image_url": "https://oldschool.runescape.wiki/images/e/e3/Dragonstone_boots.png?5eb13",
    "wiki_url": "https://oldschool.runescape.wiki/w/Dragonstone_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-3",
    "ranged_atk": "-1",
    "stab_def": "+12",
    "slash_def": "+13",
    "crush_def": "+14",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+2",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Elven boots": {
    "image_url": "https://oldschool.runescape.wiki/images/0/06/Elven_boots.png?c85b3",
    "wiki_url": "https://oldschool.runescape.wiki/w/Elven_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Eternal boots": {
    "image_url": "https://oldschool.runescape.wiki/images/e/ee/Eternal_boots.png?b8cf0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Eternal_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+8",
    "ranged_atk": "+0",
    "stab_def": "+5",
    "slash_def": "+5",
    "crush_def": "+5",
    "magic_def": "+8",
    "ranged_def": "+5",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Eternal boots (Last Man Standing)": {
    "image_url": "https://oldschool.runescape.wiki/images/a/af/Eternal_boots_%28Last_Man_Standing%29.png?b8cf0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Eternal_boots_(Last_Man_Standing)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+8",
    "ranged_atk": "+0",
    "stab_def": "+5",
    "slash_def": "+5",
    "crush_def": "+5",
    "magic_def": "+8",
    "ranged_def": "+5",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Evil chicken feet": {
    "image_url": "https://oldschool.runescape.wiki/images/0/02/Evil_chicken_feet.png?b8cf0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Evil_chicken_feet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Fancy boots": {
    "image_url": "https://oldschool.runescape.wiki/images/8/8f/Fancy_boots.png?97fe8",
    "wiki_url": "https://oldschool.runescape.wiki/w/Fancy_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-3",
    "ranged_atk": "-1",
    "stab_def": "+1",
    "slash_def": "+2",
    "crush_def": "+3",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Farmer's boots#Female": {
    "image_url": "https://oldschool.runescape.wiki/images/c/c6/Farmer%27s_boots_%28female%29.png?97fe8",
    "wiki_url": "https://oldschool.runescape.wiki/w/Farmer%27s_boots#Female",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Farmer's boots#Male": {
    "image_url": "https://oldschool.runescape.wiki/images/4/4d/Farmer%27s_boots.png?5abba",
    "wiki_url": "https://oldschool.runescape.wiki/w/Farmer%27s_boots#Male",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Fighting boots": {
    "image_url": "https://oldschool.runescape.wiki/images/f/f5/Fighting_boots.png?97fe8",
    "wiki_url": "https://oldschool.runescape.wiki/w/Fighting_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-3",
    "ranged_atk": "-1",
    "stab_def": "+1",
    "slash_def": "+2",
    "crush_def": "+3",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Flippers": {
    "image_url": "https://oldschool.runescape.wiki/images/1/14/Flippers.png?e8233",
    "wiki_url": "https://oldschool.runescape.wiki/w/Flippers",
    "stab_atk": "-2",
    "slash_atk": "-2",
    "crush_atk": "-2",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Fremennik boots": {
    "image_url": "https://oldschool.runescape.wiki/images/a/af/Fremennik_boots.png?c27d7",
    "wiki_url": "https://oldschool.runescape.wiki/w/Fremennik_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Fremennik sea boots 1": {
    "image_url": "https://oldschool.runescape.wiki/images/4/4c/Fremennik_sea_boots_1.png?c83d6",
    "wiki_url": "https://oldschool.runescape.wiki/w/Fremennik_sea_boots_1",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-3",
    "ranged_atk": "-1",
    "stab_def": "+2",
    "slash_def": "+3",
    "crush_def": "+4",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Fremennik sea boots 2": {
    "image_url": "https://oldschool.runescape.wiki/images/2/26/Fremennik_sea_boots_2.png?c83d6",
    "wiki_url": "https://oldschool.runescape.wiki/w/Fremennik_sea_boots_2",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-3",
    "ranged_atk": "-1",
    "stab_def": "+5",
    "slash_def": "+6",
    "crush_def": "+7",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Fremennik sea boots 3": {
    "image_url": "https://oldschool.runescape.wiki/images/2/22/Fremennik_sea_boots_3.png?f59ab",
    "wiki_url": "https://oldschool.runescape.wiki/w/Fremennik_sea_boots_3",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-3",
    "ranged_atk": "-1",
    "stab_def": "+7",
    "slash_def": "+8",
    "crush_def": "+9",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Fremennik sea boots 4": {
    "image_url": "https://oldschool.runescape.wiki/images/0/07/Fremennik_sea_boots_4.png?f59ab",
    "wiki_url": "https://oldschool.runescape.wiki/w/Fremennik_sea_boots_4",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+1",
    "ranged_atk": "+1",
    "stab_def": "+10",
    "slash_def": "+11",
    "crush_def": "+12",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+1",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Frog slippers": {
    "image_url": "https://oldschool.runescape.wiki/images/a/af/Frog_slippers.png?16f62",
    "wiki_url": "https://oldschool.runescape.wiki/w/Frog_slippers",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Frog-leather boots": {
    "image_url": "https://oldschool.runescape.wiki/images/8/8c/Frog-leather_boots.png?16f62",
    "wiki_url": "https://oldschool.runescape.wiki/w/Frog-leather_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-8",
    "ranged_atk": "+2",
    "stab_def": "+1",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+0",
    "ranged_def": "+1",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Gardening boots": {
    "image_url": "https://oldschool.runescape.wiki/images/3/39/Gardening_boots.png?33486",
    "wiki_url": "https://oldschool.runescape.wiki/w/Gardening_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ghostly boots": {
    "image_url": "https://oldschool.runescape.wiki/images/a/a2/Ghostly_boots.png?77553",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ghostly_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+2",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+2",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Gilded boots": {
    "image_url": "https://oldschool.runescape.wiki/images/a/a1/Gilded_boots.png?583e2",
    "wiki_url": "https://oldschool.runescape.wiki/w/Gilded_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-3",
    "ranged_atk": "-1",
    "stab_def": "+12",
    "slash_def": "+13",
    "crush_def": "+14",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+2",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Golden prospector boots": {
    "image_url": "https://oldschool.runescape.wiki/images/b/ba/Golden_prospector_boots.png?fc2ef",
    "wiki_url": "https://oldschool.runescape.wiki/w/Golden_prospector_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Graceful boots#Agility_Arena": {
    "image_url": "https://oldschool.runescape.wiki/images/1/1e/Graceful_boots_%28Agility_Arena%29.png?99c22",
    "wiki_url": "https://oldschool.runescape.wiki/w/Graceful_boots#Agility_Arena",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Graceful boots#Arceuus": {
    "image_url": "https://oldschool.runescape.wiki/images/e/eb/Graceful_boots_%28Arceuus%29.png?99c22",
    "wiki_url": "https://oldschool.runescape.wiki/w/Graceful_boots#Arceuus",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Graceful boots#Hallowed": {
    "image_url": "https://oldschool.runescape.wiki/images/7/7f/Graceful_boots_%28Hallowed%29.png?3d117",
    "wiki_url": "https://oldschool.runescape.wiki/w/Graceful_boots#Hallowed",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Graceful boots#Hosidius": {
    "image_url": "https://oldschool.runescape.wiki/images/e/e5/Graceful_boots_%28Hosidius%29.png?99c22",
    "wiki_url": "https://oldschool.runescape.wiki/w/Graceful_boots#Hosidius",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Graceful boots#Kourend": {
    "image_url": "https://oldschool.runescape.wiki/images/a/a5/Graceful_boots_%28Kourend%29.png?99c22",
    "wiki_url": "https://oldschool.runescape.wiki/w/Graceful_boots#Kourend",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Graceful boots#Lovakengj": {
    "image_url": "https://oldschool.runescape.wiki/images/3/39/Graceful_boots_%28Lovakengj%29.png?99c22",
    "wiki_url": "https://oldschool.runescape.wiki/w/Graceful_boots#Lovakengj",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Graceful boots#Piscarilius": {
    "image_url": "https://oldschool.runescape.wiki/images/5/55/Graceful_boots_%28Piscarilius%29.png?99c22",
    "wiki_url": "https://oldschool.runescape.wiki/w/Graceful_boots#Piscarilius",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Graceful boots#Regular": {
    "image_url": "https://oldschool.runescape.wiki/images/1/15/Graceful_boots.png?cf6ac",
    "wiki_url": "https://oldschool.runescape.wiki/w/Graceful_boots#Regular",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Graceful boots#Shayzien": {
    "image_url": "https://oldschool.runescape.wiki/images/2/22/Graceful_boots_%28Shayzien%29.png?3d117",
    "wiki_url": "https://oldschool.runescape.wiki/w/Graceful_boots#Shayzien",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Graceful boots#Trailblazer": {
    "image_url": "https://oldschool.runescape.wiki/images/8/89/Graceful_boots_%28Trailblazer%29.png?99c22",
    "wiki_url": "https://oldschool.runescape.wiki/w/Graceful_boots#Trailblazer",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Granite boots": {
    "image_url": "https://oldschool.runescape.wiki/images/c/c1/Granite_boots.png?e06cd",
    "wiki_url": "https://oldschool.runescape.wiki/w/Granite_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-3",
    "ranged_atk": "-1",
    "stab_def": "+15",
    "slash_def": "+16",
    "crush_def": "+17",
    "magic_def": "+0",
    "ranged_def": "+8",
    "str_bonus": "+3",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Gravedigger boots#During_event": {
    "image_url": "https://oldschool.runescape.wiki/images/5/5d/Gravedigger_boots.png?19135",
    "wiki_url": "https://oldschool.runescape.wiki/w/Gravedigger_boots#During_event",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Gravedigger boots#Reward": {
    "image_url": "https://oldschool.runescape.wiki/images/5/5d/Gravedigger_boots.png?19135",
    "wiki_url": "https://oldschool.runescape.wiki/w/Gravedigger_boots#Reward",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Green boots": {
    "image_url": "https://oldschool.runescape.wiki/images/3/39/Green_boots.png?e06cd",
    "wiki_url": "https://oldschool.runescape.wiki/w/Green_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Grey boots": {
    "image_url": "https://oldschool.runescape.wiki/images/d/d6/Grey_boots.png?e75c0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Grey_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Guardian boots": {
    "image_url": "https://oldschool.runescape.wiki/images/8/84/Guardian_boots.png?d316a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Guardian_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-3",
    "ranged_atk": "-1",
    "stab_def": "+32",
    "slash_def": "+32",
    "crush_def": "+32",
    "magic_def": "-3",
    "ranged_def": "+24",
    "str_bonus": "+3",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+2"
  },
  "Guthix d'hide boots": {
    "image_url": "https://oldschool.runescape.wiki/images/8/86/Guthix_d%27hide_boots.png?d316a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Guthix_d%27hide_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-10",
    "ranged_atk": "+7",
    "stab_def": "+4",
    "slash_def": "+4",
    "crush_def": "+4",
    "magic_def": "+4",
    "ranged_def": "+4",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+1"
  },
  "Ham boots": {
    "image_url": "https://oldschool.runescape.wiki/images/4/41/Ham_boots.png?64612",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ham_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Holy sandals": {
    "image_url": "https://oldschool.runescape.wiki/images/3/37/Holy_sandals.png?53fc0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Holy_sandals",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+3"
  },
  "Infinity boots": {
    "image_url": "https://oldschool.runescape.wiki/images/d/d8/Infinity_boots.png?19317",
    "wiki_url": "https://oldschool.runescape.wiki/w/Infinity_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+5",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+5",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Insulated boots": {
    "image_url": "https://oldschool.runescape.wiki/images/6/65/Insulated_boots.png?19317",
    "wiki_url": "https://oldschool.runescape.wiki/w/Insulated_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+1",
    "slash_def": "+1",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+1",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Iron boots": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b4/Iron_boots.png?b51d2",
    "wiki_url": "https://oldschool.runescape.wiki/w/Iron_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-3",
    "ranged_atk": "-1",
    "stab_def": "+2",
    "slash_def": "+3",
    "crush_def": "+4",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Leather boots": {
    "image_url": "https://oldschool.runescape.wiki/images/e/ea/Leather_boots.png?a6990",
    "wiki_url": "https://oldschool.runescape.wiki/w/Leather_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Light tuxedo shoes": {
    "image_url": "https://oldschool.runescape.wiki/images/9/94/Light_tuxedo_shoes.png?a6990",
    "wiki_url": "https://oldschool.runescape.wiki/w/Light_tuxedo_shoes",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Lumberjack boots": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b3/Lumberjack_boots.png?ed6d0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Lumberjack_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Lunar boots": {
    "image_url": "https://oldschool.runescape.wiki/images/8/84/Lunar_boots.png?8bd5a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Lunar_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+2",
    "ranged_atk": "-1",
    "stab_def": "+1",
    "slash_def": "+2",
    "crush_def": "+2",
    "magic_def": "+2",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Mime boots": {
    "image_url": "https://oldschool.runescape.wiki/images/8/8b/Mime_boots.png?ccf02",
    "wiki_url": "https://oldschool.runescape.wiki/w/Mime_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Mithril boots": {
    "image_url": "https://oldschool.runescape.wiki/images/e/e1/Mithril_boots.png?ccf02",
    "wiki_url": "https://oldschool.runescape.wiki/w/Mithril_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-3",
    "ranged_atk": "-1",
    "stab_def": "+8",
    "slash_def": "+9",
    "crush_def": "+10",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Mole slippers": {
    "image_url": "https://oldschool.runescape.wiki/images/1/19/Mole_slippers.png?8cc7e",
    "wiki_url": "https://oldschool.runescape.wiki/w/Mole_slippers",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Moonclan boots": {
    "image_url": "https://oldschool.runescape.wiki/images/3/3a/Moonclan_boots.png?7027d",
    "wiki_url": "https://oldschool.runescape.wiki/w/Moonclan_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+2",
    "ranged_atk": "-5",
    "stab_def": "+2",
    "slash_def": "+2",
    "crush_def": "+2",
    "magic_def": "+2",
    "ranged_def": "-5",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Mourner boots": {
    "image_url": "https://oldschool.runescape.wiki/images/e/e7/Mourner_boots.png?fa8bd",
    "wiki_url": "https://oldschool.runescape.wiki/w/Mourner_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Mummy's feet": {
    "image_url": "https://oldschool.runescape.wiki/images/b/be/Mummy%27s_feet.png?7027d",
    "wiki_url": "https://oldschool.runescape.wiki/w/Mummy%27s_feet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Mystic boots": {
    "image_url": "https://oldschool.runescape.wiki/images/c/c1/Mystic_boots.png?246bf",
    "wiki_url": "https://oldschool.runescape.wiki/w/Mystic_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+3",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+3",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Mystic boots (dark)": {
    "image_url": "https://oldschool.runescape.wiki/images/0/08/Mystic_boots_%28dark%29.png?ed6d0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Mystic_boots_(dark)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+3",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+3",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Mystic boots (dusk)": {
    "image_url": "https://oldschool.runescape.wiki/images/f/f4/Mystic_boots_%28dusk%29.png?6ac0d",
    "wiki_url": "https://oldschool.runescape.wiki/w/Mystic_boots_(dusk)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+3",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+3",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Mystic boots (light)": {
    "image_url": "https://oldschool.runescape.wiki/images/b/bf/Mystic_boots_%28light%29.png?df7b3",
    "wiki_url": "https://oldschool.runescape.wiki/w/Mystic_boots_(light)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+3",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+3",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ornate boots": {
    "image_url": "https://oldschool.runescape.wiki/images/9/9f/Ornate_boots.png?de02e",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ornate_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Pegasian boots": {
    "image_url": "https://oldschool.runescape.wiki/images/7/71/Pegasian_boots.png?97482",
    "wiki_url": "https://oldschool.runescape.wiki/w/Pegasian_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-12",
    "ranged_atk": "+12",
    "stab_def": "+5",
    "slash_def": "+5",
    "crush_def": "+5",
    "magic_def": "+5",
    "ranged_def": "+5",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Pink boots": {
    "image_url": "https://oldschool.runescape.wiki/images/5/52/Pink_boots.png?219da",
    "wiki_url": "https://oldschool.runescape.wiki/w/Pink_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Pirate boots": {
    "image_url": "https://oldschool.runescape.wiki/images/f/fd/Pirate_boots.png?f976b",
    "wiki_url": "https://oldschool.runescape.wiki/w/Pirate_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Primordial boots": {
    "image_url": "https://oldschool.runescape.wiki/images/4/42/Primordial_boots.png?e2ec4",
    "wiki_url": "https://oldschool.runescape.wiki/w/Primordial_boots",
    "stab_atk": "+2",
    "slash_atk": "+2",
    "crush_atk": "+2",
    "magic_atk": "-4",
    "ranged_atk": "-1",
    "stab_def": "+22",
    "slash_def": "+22",
    "crush_def": "+22",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+5",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Prospector boots": {
    "image_url": "https://oldschool.runescape.wiki/images/3/30/Prospector_boots.png?281b5",
    "wiki_url": "https://oldschool.runescape.wiki/w/Prospector_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Purple boots": {
    "image_url": "https://oldschool.runescape.wiki/images/5/5a/Purple_boots.png?3a750",
    "wiki_url": "https://oldschool.runescape.wiki/w/Purple_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Pyromancer boots": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b4/Pyromancer_boots.png?ed4b0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Pyromancer_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ranger boots": {
    "image_url": "https://oldschool.runescape.wiki/images/f/f3/Ranger_boots.png?9a45f",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ranger_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-10",
    "ranged_atk": "+8",
    "stab_def": "+2",
    "slash_def": "+3",
    "crush_def": "+4",
    "magic_def": "+2",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Red boots": {
    "image_url": "https://oldschool.runescape.wiki/images/a/ad/Red_boots.png?cb76b",
    "wiki_url": "https://oldschool.runescape.wiki/w/Red_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Rock-shell boots": {
    "image_url": "https://oldschool.runescape.wiki/images/8/8d/Rock-shell_boots.png?43f24",
    "wiki_url": "https://oldschool.runescape.wiki/w/Rock-shell_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Rogue boots": {
    "image_url": "https://oldschool.runescape.wiki/images/d/df/Rogue_boots.png?43f24",
    "wiki_url": "https://oldschool.runescape.wiki/w/Rogue_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+2",
    "slash_def": "+2",
    "crush_def": "+2",
    "magic_def": "+2",
    "ranged_def": "+2",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Rune boots": {
    "image_url": "https://oldschool.runescape.wiki/images/e/e8/Rune_boots.png?eec05",
    "wiki_url": "https://oldschool.runescape.wiki/w/Rune_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-3",
    "ranged_atk": "-1",
    "stab_def": "+12",
    "slash_def": "+13",
    "crush_def": "+14",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+2",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Runner boots": {
    "image_url": "https://oldschool.runescape.wiki/images/6/6b/Runner_boots.png?068bd",
    "wiki_url": "https://oldschool.runescape.wiki/w/Runner_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+1",
    "ranged_atk": "+1",
    "stab_def": "+8",
    "slash_def": "+8",
    "crush_def": "+8",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Samurai boots": {
    "image_url": "https://oldschool.runescape.wiki/images/1/19/Samurai_boots.png?a8fa6",
    "wiki_url": "https://oldschool.runescape.wiki/w/Samurai_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+11",
    "slash_def": "+12",
    "crush_def": "+13",
    "magic_def": "+1",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Santa boots": {
    "image_url": "https://oldschool.runescape.wiki/images/c/c7/Santa_boots.png?dcaa9",
    "wiki_url": "https://oldschool.runescape.wiki/w/Santa_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Saradomin d'hide boots": {
    "image_url": "https://oldschool.runescape.wiki/images/4/40/Saradomin_d%27hide_boots.png?847d4",
    "wiki_url": "https://oldschool.runescape.wiki/w/Saradomin_d%27hide_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-10",
    "ranged_atk": "+7",
    "stab_def": "+4",
    "slash_def": "+4",
    "crush_def": "+4",
    "magic_def": "+4",
    "ranged_def": "+4",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+1"
  },
  "Shayzien boots (1)": {
    "image_url": "https://oldschool.runescape.wiki/images/6/6f/Shayzien_boots_%281%29.png?4b960",
    "wiki_url": "https://oldschool.runescape.wiki/w/Shayzien_boots_(1)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-2",
    "ranged_atk": "-1",
    "stab_def": "+1",
    "slash_def": "+2",
    "crush_def": "+3",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Shayzien boots (2)": {
    "image_url": "https://oldschool.runescape.wiki/images/a/a1/Shayzien_boots_%282%29.png?4b960",
    "wiki_url": "https://oldschool.runescape.wiki/w/Shayzien_boots_(2)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-2",
    "ranged_atk": "-1",
    "stab_def": "+2",
    "slash_def": "+3",
    "crush_def": "+4",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Shayzien boots (3)": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b7/Shayzien_boots_%283%29.png?3caa3",
    "wiki_url": "https://oldschool.runescape.wiki/w/Shayzien_boots_(3)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-2",
    "ranged_atk": "-1",
    "stab_def": "+4",
    "slash_def": "+5",
    "crush_def": "+6",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Shayzien boots (4)": {
    "image_url": "https://oldschool.runescape.wiki/images/5/5d/Shayzien_boots_%284%29.png?c943f",
    "wiki_url": "https://oldschool.runescape.wiki/w/Shayzien_boots_(4)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-2",
    "ranged_atk": "-1",
    "stab_def": "+5",
    "slash_def": "+6",
    "crush_def": "+7",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Shayzien boots (5)": {
    "image_url": "https://oldschool.runescape.wiki/images/4/4d/Shayzien_boots_%285%29.png?c943f",
    "wiki_url": "https://oldschool.runescape.wiki/w/Shayzien_boots_(5)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-2",
    "ranged_atk": "+4",
    "stab_def": "+5",
    "slash_def": "+7",
    "crush_def": "+8",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Shoes": {
    "image_url": "https://oldschool.runescape.wiki/images/8/82/Shoes.png?3caa3",
    "wiki_url": "https://oldschool.runescape.wiki/w/Shoes",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Silly jester boots": {
    "image_url": "https://oldschool.runescape.wiki/images/e/e5/Silly_jester_boots.png?199d1",
    "wiki_url": "https://oldschool.runescape.wiki/w/Silly_jester_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+5",
    "ranged_def": "-5",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Skeletal boots": {
    "image_url": "https://oldschool.runescape.wiki/images/0/0e/Skeletal_boots.png?7fb98",
    "wiki_url": "https://oldschool.runescape.wiki/w/Skeletal_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Skeleton boots": {
    "image_url": "https://oldschool.runescape.wiki/images/5/5b/Skeleton_boots.png?0df0a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Skeleton_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Slave boots": {
    "image_url": "https://oldschool.runescape.wiki/images/5/5d/Slave_boots.png?0df0a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Slave_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Snakeskin boots": {
    "image_url": "https://oldschool.runescape.wiki/images/4/42/Snakeskin_boots.png?aa1e9",
    "wiki_url": "https://oldschool.runescape.wiki/w/Snakeskin_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-10",
    "ranged_atk": "+3",
    "stab_def": "+1",
    "slash_def": "+1",
    "crush_def": "+2",
    "magic_def": "+1",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Snow imp costume feet#During_event": {
    "image_url": "https://oldschool.runescape.wiki/images/f/f6/Snow_imp_costume_feet.png?7e966",
    "wiki_url": "https://oldschool.runescape.wiki/w/Snow_imp_costume_feet#During_event",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Snow imp costume feet#Reward": {
    "image_url": "https://oldschool.runescape.wiki/images/f/f6/Snow_imp_costume_feet.png?7e966",
    "wiki_url": "https://oldschool.runescape.wiki/w/Snow_imp_costume_feet#Reward",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Spiked boots": {
    "image_url": "https://oldschool.runescape.wiki/images/f/f1/Spiked_boots.png?848ff",
    "wiki_url": "https://oldschool.runescape.wiki/w/Spiked_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+2",
    "crush_def": "+2",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+2",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Spiked manacles": {
    "image_url": "https://oldschool.runescape.wiki/images/e/e5/Spiked_manacles.png?e8969",
    "wiki_url": "https://oldschool.runescape.wiki/w/Spiked_manacles",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-3",
    "ranged_atk": "-1",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "-4",
    "ranged_def": "+0",
    "str_bonus": "+4",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Spined boots": {
    "image_url": "https://oldschool.runescape.wiki/images/d/d3/Spined_boots.png?e8969",
    "wiki_url": "https://oldschool.runescape.wiki/w/Spined_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Spirit angler boots": {
    "image_url": "https://oldschool.runescape.wiki/images/e/e1/Spirit_angler_boots.png?e8969",
    "wiki_url": "https://oldschool.runescape.wiki/w/Spirit_angler_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Splitbark boots": {
    "image_url": "https://oldschool.runescape.wiki/images/4/43/Splitbark_boots.png?e8969",
    "wiki_url": "https://oldschool.runescape.wiki/w/Splitbark_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+2",
    "ranged_atk": "-1",
    "stab_def": "+3",
    "slash_def": "+2",
    "crush_def": "+4",
    "magic_def": "+2",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Spookier boots": {
    "image_url": "https://oldschool.runescape.wiki/images/3/34/Spookier_boots.png?717c8",
    "wiki_url": "https://oldschool.runescape.wiki/w/Spookier_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Spooky boots#Reward": {
    "image_url": "https://oldschool.runescape.wiki/images/c/c0/Spooky_boots.png?8dbbb",
    "wiki_url": "https://oldschool.runescape.wiki/w/Spooky_boots#Reward",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Steel boots": {
    "image_url": "https://oldschool.runescape.wiki/images/9/98/Steel_boots.png?3203e",
    "wiki_url": "https://oldschool.runescape.wiki/w/Steel_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-3",
    "ranged_atk": "-1",
    "stab_def": "+5",
    "slash_def": "+6",
    "crush_def": "+7",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Swampbark boots": {
    "image_url": "https://oldschool.runescape.wiki/images/c/c3/Swampbark_boots.png?fa231",
    "wiki_url": "https://oldschool.runescape.wiki/w/Swampbark_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+3",
    "ranged_atk": "+0",
    "stab_def": "+4",
    "slash_def": "+3",
    "crush_def": "+5",
    "magic_def": "+4",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Teal boots": {
    "image_url": "https://oldschool.runescape.wiki/images/f/fc/Teal_boots.png?fa231",
    "wiki_url": "https://oldschool.runescape.wiki/w/Teal_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Trailblazer boots (t1)": {
    "image_url": "https://oldschool.runescape.wiki/images/1/1b/Trailblazer_boots_%28t1%29.png?79f0d",
    "wiki_url": "https://oldschool.runescape.wiki/w/Trailblazer_boots_(t1)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Trailblazer boots (t2)": {
    "image_url": "https://oldschool.runescape.wiki/images/4/43/Trailblazer_boots_%28t2%29.png?5c5a6",
    "wiki_url": "https://oldschool.runescape.wiki/w/Trailblazer_boots_(t2)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Trailblazer boots (t3)": {
    "image_url": "https://oldschool.runescape.wiki/images/2/28/Trailblazer_boots_%28t3%29.png?79f0d",
    "wiki_url": "https://oldschool.runescape.wiki/w/Trailblazer_boots_(t3)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Turquoise boots": {
    "image_url": "https://oldschool.runescape.wiki/images/e/ea/Turquoise_boots.png?5c5a6",
    "wiki_url": "https://oldschool.runescape.wiki/w/Turquoise_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Twisted boots (t1)": {
    "image_url": "https://oldschool.runescape.wiki/images/e/e4/Twisted_boots_%28t1%29.png?2ffa5",
    "wiki_url": "https://oldschool.runescape.wiki/w/Twisted_boots_(t1)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Twisted boots (t2)": {
    "image_url": "https://oldschool.runescape.wiki/images/e/e0/Twisted_boots_%28t2%29.png?5c5a6",
    "wiki_url": "https://oldschool.runescape.wiki/w/Twisted_boots_(t2)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Twisted boots (t3)": {
    "image_url": "https://oldschool.runescape.wiki/images/2/29/Twisted_boots_%28t3%29.png?5c5a6",
    "wiki_url": "https://oldschool.runescape.wiki/w/Twisted_boots_(t3)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Villager sandals (blue)": {
    "image_url": "https://oldschool.runescape.wiki/images/a/a6/Villager_sandals_%28blue%29.png?4afbb",
    "wiki_url": "https://oldschool.runescape.wiki/w/Villager_sandals_(blue)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Villager sandals (brown)": {
    "image_url": "https://oldschool.runescape.wiki/images/8/81/Villager_sandals_%28brown%29.png?43659",
    "wiki_url": "https://oldschool.runescape.wiki/w/Villager_sandals_(brown)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Villager sandals (pink)": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b6/Villager_sandals_%28pink%29.png?a7de8",
    "wiki_url": "https://oldschool.runescape.wiki/w/Villager_sandals_(pink)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Villager sandals (yellow)": {
    "image_url": "https://oldschool.runescape.wiki/images/6/6c/Villager_sandals_%28yellow%29.png?4afbb",
    "wiki_url": "https://oldschool.runescape.wiki/w/Villager_sandals_(yellow)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Vyre noble shoes": {
    "image_url": "https://oldschool.runescape.wiki/images/7/7d/Vyre_noble_shoes.png?bc0cd",
    "wiki_url": "https://oldschool.runescape.wiki/w/Vyre_noble_shoes",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Vyrewatch shoes": {
    "image_url": "https://oldschool.runescape.wiki/images/9/97/Vyrewatch_shoes.png?9e8ff",
    "wiki_url": "https://oldschool.runescape.wiki/w/Vyrewatch_shoes",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+2",
    "crush_def": "+2",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "White boots": {
    "image_url": "https://oldschool.runescape.wiki/images/7/71/White_boots.png?f5d8b",
    "wiki_url": "https://oldschool.runescape.wiki/w/White_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-3",
    "ranged_atk": "-1",
    "stab_def": "+7",
    "slash_def": "+8",
    "crush_def": "+9",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+1"
  },
  "Wizard boots": {
    "image_url": "https://oldschool.runescape.wiki/images/9/99/Wizard_boots.png?d2390",
    "wiki_url": "https://oldschool.runescape.wiki/w/Wizard_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+4",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+4",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Yellow boots": {
    "image_url": "https://oldschool.runescape.wiki/images/9/9b/Yellow_boots.png?7e7a8",
    "wiki_url": "https://oldschool.runescape.wiki/w/Yellow_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Zamorak d'hide boots": {
    "image_url": "https://oldschool.runescape.wiki/images/7/74/Zamorak_d%27hide_boots.png?37c64",
    "wiki_url": "https://oldschool.runescape.wiki/w/Zamorak_d%27hide_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-10",
    "ranged_atk": "+7",
    "stab_def": "+4",
    "slash_def": "+4",
    "crush_def": "+4",
    "magic_def": "+4",
    "ranged_def": "+4",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+1"
  },
  "Zealot's boots": {
    "image_url": "https://oldschool.runescape.wiki/images/5/57/Zealot%27s_boots.png?37c64",
    "wiki_url": "https://oldschool.runescape.wiki/w/Zealot%27s_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+1"
  },
  "Zombie boots": {
    "image_url": "https://oldschool.runescape.wiki/images/c/c4/Zombie_boots.png?53a8d",
    "wiki_url": "https://oldschool.runescape.wiki/w/Zombie_boots",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  }
}