window.equipment.hands = {
  "20th anniversary gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/f/fc/20th_anniversary_gloves.png?3e370",
    "wiki_url": "https://oldschool.runescape.wiki/w/20th_anniversary_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "3rd age vambraces": {
    "image_url": "https://oldschool.runescape.wiki/images/8/8d/3rd_age_vambraces.png?bfd18",
    "wiki_url": "https://oldschool.runescape.wiki/w/3rd_age_vambraces",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-10",
    "ranged_atk": "+11",
    "stab_def": "+6",
    "slash_def": "+5",
    "crush_def": "+7",
    "magic_def": "+9",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Abyssal bracelet#(1)": {
    "image_url": "https://oldschool.runescape.wiki/images/5/54/Abyssal_bracelet.png?c04be",
    "wiki_url": "https://oldschool.runescape.wiki/w/Abyssal_bracelet#(1)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Abyssal bracelet#(2)": {
    "image_url": "https://oldschool.runescape.wiki/images/5/54/Abyssal_bracelet.png?c04be",
    "wiki_url": "https://oldschool.runescape.wiki/w/Abyssal_bracelet#(2)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Abyssal bracelet#(3)": {
    "image_url": "https://oldschool.runescape.wiki/images/5/54/Abyssal_bracelet.png?c04be",
    "wiki_url": "https://oldschool.runescape.wiki/w/Abyssal_bracelet#(3)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Abyssal bracelet#(4)": {
    "image_url": "https://oldschool.runescape.wiki/images/5/54/Abyssal_bracelet.png?c04be",
    "wiki_url": "https://oldschool.runescape.wiki/w/Abyssal_bracelet#(4)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Abyssal bracelet#(5)": {
    "image_url": "https://oldschool.runescape.wiki/images/5/54/Abyssal_bracelet.png?c04be",
    "wiki_url": "https://oldschool.runescape.wiki/w/Abyssal_bracelet#(5)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Adamant gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/6/6b/Adamant_gloves.png?63d9c",
    "wiki_url": "https://oldschool.runescape.wiki/w/Adamant_gloves",
    "stab_atk": "+7",
    "slash_atk": "+7",
    "crush_atk": "+7",
    "magic_atk": "+4",
    "ranged_atk": "+7",
    "stab_def": "+7",
    "slash_def": "+7",
    "crush_def": "+7",
    "magic_def": "+4",
    "ranged_def": "+7",
    "str_bonus": "+7",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Adamant gloves (Last Man Standing)": {
    "image_url": "https://oldschool.runescape.wiki/images/2/21/Adamant_gloves_%28Last_Man_Standing%29.png?05955",
    "wiki_url": "https://oldschool.runescape.wiki/w/Adamant_gloves_(Last_Man_Standing)",
    "stab_atk": "+7",
    "slash_atk": "+7",
    "crush_atk": "+7",
    "magic_atk": "+4",
    "ranged_atk": "+7",
    "stab_def": "+7",
    "slash_def": "+7",
    "crush_def": "+7",
    "magic_def": "+4",
    "ranged_def": "+7",
    "str_bonus": "+7",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ancient bracers": {
    "image_url": "https://oldschool.runescape.wiki/images/8/85/Ancient_bracers.png?15de7",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ancient_bracers",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-10",
    "ranged_atk": "+11",
    "stab_def": "+6",
    "slash_def": "+5",
    "crush_def": "+7",
    "magic_def": "+8",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+1"
  },
  "Ankou gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/1/16/Ankou_gloves.png?f0f17",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ankou_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Antisanta gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/1/1a/Antisanta_gloves.png?38864",
    "wiki_url": "https://oldschool.runescape.wiki/w/Antisanta_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Armadyl bracers": {
    "image_url": "https://oldschool.runescape.wiki/images/c/ca/Armadyl_bracers.png?e56f0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Armadyl_bracers",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-10",
    "ranged_atk": "+11",
    "stab_def": "+6",
    "slash_def": "+5",
    "crush_def": "+7",
    "magic_def": "+8",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+1"
  },
  "Bandos bracers": {
    "image_url": "https://oldschool.runescape.wiki/images/7/7b/Bandos_bracers.png?f928c",
    "wiki_url": "https://oldschool.runescape.wiki/w/Bandos_bracers",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-10",
    "ranged_atk": "+11",
    "stab_def": "+6",
    "slash_def": "+5",
    "crush_def": "+7",
    "magic_def": "+8",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+1"
  },
  "Barrows gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/b/bf/Barrows_gloves.png?3be33",
    "wiki_url": "https://oldschool.runescape.wiki/w/Barrows_gloves",
    "stab_atk": "+12",
    "slash_atk": "+12",
    "crush_atk": "+12",
    "magic_atk": "+6",
    "ranged_atk": "+12",
    "stab_def": "+12",
    "slash_def": "+12",
    "crush_def": "+12",
    "magic_def": "+6",
    "ranged_def": "+12",
    "str_bonus": "+12",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Barrows gloves (Last Man Standing)": {
    "image_url": "https://oldschool.runescape.wiki/images/2/26/Barrows_gloves_%28Last_Man_Standing%29.png?78f79",
    "wiki_url": "https://oldschool.runescape.wiki/w/Barrows_gloves_(Last_Man_Standing)",
    "stab_atk": "+12",
    "slash_atk": "+12",
    "crush_atk": "+12",
    "magic_atk": "+6",
    "ranged_atk": "+12",
    "stab_def": "+12",
    "slash_def": "+12",
    "crush_def": "+12",
    "magic_def": "+6",
    "ranged_def": "+12",
    "str_bonus": "+12",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Beekeeper's gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/3/35/Beekeeper%27s_gloves.png?3be33",
    "wiki_url": "https://oldschool.runescape.wiki/w/Beekeeper%27s_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Black d'hide vambraces": {
    "image_url": "https://oldschool.runescape.wiki/images/1/1b/Black_d%27hide_vambraces.png?db3d9",
    "wiki_url": "https://oldschool.runescape.wiki/w/Black_d%27hide_vambraces",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-10",
    "ranged_atk": "+11",
    "stab_def": "+6",
    "slash_def": "+5",
    "crush_def": "+7",
    "magic_def": "+8",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Black gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/8/82/Black_gloves.png?0a33f",
    "wiki_url": "https://oldschool.runescape.wiki/w/Black_gloves",
    "stab_atk": "+5",
    "slash_atk": "+5",
    "crush_atk": "+5",
    "magic_atk": "+3",
    "ranged_atk": "+5",
    "stab_def": "+5",
    "slash_def": "+5",
    "crush_def": "+5",
    "magic_def": "+3",
    "ranged_def": "+5",
    "str_bonus": "+5",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Black spiky vambraces": {
    "image_url": "https://oldschool.runescape.wiki/images/5/53/Black_spiky_vambraces.png?5e74f",
    "wiki_url": "https://oldschool.runescape.wiki/w/Black_spiky_vambraces",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-10",
    "ranged_atk": "+11",
    "stab_def": "+6",
    "slash_def": "+5",
    "crush_def": "+7",
    "magic_def": "+8",
    "ranged_def": "+0",
    "str_bonus": "+2",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Bloodbark gauntlets": {
    "image_url": "https://oldschool.runescape.wiki/images/f/fc/Bloodbark_gauntlets.png?d13d3",
    "wiki_url": "https://oldschool.runescape.wiki/w/Bloodbark_gauntlets",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+4",
    "ranged_atk": "+0",
    "stab_def": "+5",
    "slash_def": "+4",
    "crush_def": "+6",
    "magic_def": "+5",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Blue d'hide vambraces": {
    "image_url": "https://oldschool.runescape.wiki/images/3/31/Blue_d%27hide_vambraces.png?75625",
    "wiki_url": "https://oldschool.runescape.wiki/w/Blue_d%27hide_vambraces",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-10",
    "ranged_atk": "+9",
    "stab_def": "+4",
    "slash_def": "+3",
    "crush_def": "+5",
    "magic_def": "+4",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Blue spiky vambraces": {
    "image_url": "https://oldschool.runescape.wiki/images/3/3e/Blue_spiky_vambraces.png?4e92f",
    "wiki_url": "https://oldschool.runescape.wiki/w/Blue_spiky_vambraces",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-10",
    "ranged_atk": "+9",
    "stab_def": "+4",
    "slash_def": "+3",
    "crush_def": "+5",
    "magic_def": "+4",
    "ranged_def": "+0",
    "str_bonus": "+2",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Bracelet of clay": {
    "image_url": "https://oldschool.runescape.wiki/images/3/3d/Bracelet_of_clay.png?919da",
    "wiki_url": "https://oldschool.runescape.wiki/w/Bracelet_of_clay",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Bracelet of ethereum#Charged": {
    "image_url": "https://oldschool.runescape.wiki/images/5/5c/Bracelet_of_ethereum.png?05d25",
    "wiki_url": "https://oldschool.runescape.wiki/w/Bracelet_of_ethereum#Charged",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Bracelet of ethereum#Uncharged": {
    "image_url": "https://oldschool.runescape.wiki/images/5/56/Bracelet_of_ethereum_%28uncharged%29.png?919da",
    "wiki_url": "https://oldschool.runescape.wiki/w/Bracelet_of_ethereum#Uncharged",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Bracelet of slaughter": {
    "image_url": "https://oldschool.runescape.wiki/images/9/9e/Bracelet_of_slaughter.png?919da",
    "wiki_url": "https://oldschool.runescape.wiki/w/Bracelet_of_slaughter",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Bronze gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/4/4f/Bronze_gloves.png?cd939",
    "wiki_url": "https://oldschool.runescape.wiki/w/Bronze_gloves",
    "stab_atk": "+2",
    "slash_atk": "+2",
    "crush_atk": "+2",
    "magic_atk": "+1",
    "ranged_atk": "+2",
    "stab_def": "+2",
    "slash_def": "+2",
    "crush_def": "+2",
    "magic_def": "+1",
    "ranged_def": "+2",
    "str_bonus": "+2",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Bunny paws": {
    "image_url": "https://oldschool.runescape.wiki/images/4/4a/Bunny_paws.png?56d17",
    "wiki_url": "https://oldschool.runescape.wiki/w/Bunny_paws",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Castle wars bracelet#(1)": {
    "image_url": "https://oldschool.runescape.wiki/images/a/a2/Castle_wars_bracelet.png?3c432",
    "wiki_url": "https://oldschool.runescape.wiki/w/Castle_wars_bracelet#(1)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Castle wars bracelet#(2)": {
    "image_url": "https://oldschool.runescape.wiki/images/a/a2/Castle_wars_bracelet.png?3c432",
    "wiki_url": "https://oldschool.runescape.wiki/w/Castle_wars_bracelet#(2)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Castle wars bracelet#(3)": {
    "image_url": "https://oldschool.runescape.wiki/images/a/a2/Castle_wars_bracelet.png?3c432",
    "wiki_url": "https://oldschool.runescape.wiki/w/Castle_wars_bracelet#(3)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Chaos gauntlets": {
    "image_url": "https://oldschool.runescape.wiki/images/1/10/Chaos_gauntlets.png?3fbd5",
    "wiki_url": "https://oldschool.runescape.wiki/w/Chaos_gauntlets",
    "stab_atk": "+2",
    "slash_atk": "+2",
    "crush_atk": "+2",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+8",
    "slash_def": "+9",
    "crush_def": "+7",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+2",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Clue hunter gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/6/68/Clue_hunter_gloves.png?09bb0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Clue_hunter_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+2",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Combat bracelet#(1)": {
    "image_url": "https://oldschool.runescape.wiki/images/5/59/Combat_bracelet.png?43e7d",
    "wiki_url": "https://oldschool.runescape.wiki/w/Combat_bracelet#(1)",
    "stab_atk": "+7",
    "slash_atk": "+7",
    "crush_atk": "+7",
    "magic_atk": "+3",
    "ranged_atk": "+7",
    "stab_def": "+5",
    "slash_def": "+5",
    "crush_def": "+5",
    "magic_def": "+3",
    "ranged_def": "+5",
    "str_bonus": "+6",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Combat bracelet#(2)": {
    "image_url": "https://oldschool.runescape.wiki/images/5/59/Combat_bracelet.png?43e7d",
    "wiki_url": "https://oldschool.runescape.wiki/w/Combat_bracelet#(2)",
    "stab_atk": "+7",
    "slash_atk": "+7",
    "crush_atk": "+7",
    "magic_atk": "+3",
    "ranged_atk": "+7",
    "stab_def": "+5",
    "slash_def": "+5",
    "crush_def": "+5",
    "magic_def": "+3",
    "ranged_def": "+5",
    "str_bonus": "+6",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Combat bracelet#(3)": {
    "image_url": "https://oldschool.runescape.wiki/images/5/59/Combat_bracelet.png?43e7d",
    "wiki_url": "https://oldschool.runescape.wiki/w/Combat_bracelet#(3)",
    "stab_atk": "+7",
    "slash_atk": "+7",
    "crush_atk": "+7",
    "magic_atk": "+3",
    "ranged_atk": "+7",
    "stab_def": "+5",
    "slash_def": "+5",
    "crush_def": "+5",
    "magic_def": "+3",
    "ranged_def": "+5",
    "str_bonus": "+6",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Combat bracelet#(4)": {
    "image_url": "https://oldschool.runescape.wiki/images/5/59/Combat_bracelet.png?43e7d",
    "wiki_url": "https://oldschool.runescape.wiki/w/Combat_bracelet#(4)",
    "stab_atk": "+7",
    "slash_atk": "+7",
    "crush_atk": "+7",
    "magic_atk": "+3",
    "ranged_atk": "+7",
    "stab_def": "+5",
    "slash_def": "+5",
    "crush_def": "+5",
    "magic_def": "+3",
    "ranged_def": "+5",
    "str_bonus": "+6",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Combat bracelet#(5)": {
    "image_url": "https://oldschool.runescape.wiki/images/5/59/Combat_bracelet.png?43e7d",
    "wiki_url": "https://oldschool.runescape.wiki/w/Combat_bracelet#(5)",
    "stab_atk": "+7",
    "slash_atk": "+7",
    "crush_atk": "+7",
    "magic_atk": "+3",
    "ranged_atk": "+7",
    "stab_def": "+5",
    "slash_def": "+5",
    "crush_def": "+5",
    "magic_def": "+3",
    "ranged_def": "+5",
    "str_bonus": "+6",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Combat bracelet#(6)": {
    "image_url": "https://oldschool.runescape.wiki/images/5/59/Combat_bracelet.png?43e7d",
    "wiki_url": "https://oldschool.runescape.wiki/w/Combat_bracelet#(6)",
    "stab_atk": "+7",
    "slash_atk": "+7",
    "crush_atk": "+7",
    "magic_atk": "+3",
    "ranged_atk": "+7",
    "stab_def": "+5",
    "slash_def": "+5",
    "crush_def": "+5",
    "magic_def": "+3",
    "ranged_def": "+5",
    "str_bonus": "+6",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Combat bracelet#Uncharged": {
    "image_url": "https://oldschool.runescape.wiki/images/d/dc/Combat_bracelet_%28uncharged%29.png?43e7d",
    "wiki_url": "https://oldschool.runescape.wiki/w/Combat_bracelet#Uncharged",
    "stab_atk": "+7",
    "slash_atk": "+7",
    "crush_atk": "+7",
    "magic_atk": "+3",
    "ranged_atk": "+7",
    "stab_def": "+5",
    "slash_def": "+5",
    "crush_def": "+5",
    "magic_def": "+3",
    "ranged_def": "+5",
    "str_bonus": "+6",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Cooking gauntlets": {
    "image_url": "https://oldschool.runescape.wiki/images/9/9a/Cooking_gauntlets.png?2aac1",
    "wiki_url": "https://oldschool.runescape.wiki/w/Cooking_gauntlets",
    "stab_atk": "+2",
    "slash_atk": "+2",
    "crush_atk": "+2",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+8",
    "slash_def": "+9",
    "crush_def": "+7",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+2",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Cow gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/e/e2/Cow_gloves.png?1f2bc",
    "wiki_url": "https://oldschool.runescape.wiki/w/Cow_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Crab claw": {
    "image_url": "https://oldschool.runescape.wiki/images/e/e1/Crab_claw.png?720eb",
    "wiki_url": "https://oldschool.runescape.wiki/w/Crab_claw",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+3",
    "slash_def": "+4",
    "crush_def": "+2",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+1",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Crabclaw hook": {
    "image_url": "https://oldschool.runescape.wiki/images/4/4d/Crabclaw_hook.png?720eb",
    "wiki_url": "https://oldschool.runescape.wiki/w/Crabclaw_hook",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+3",
    "slash_def": "+5",
    "crush_def": "+3",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+1",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Dark tuxedo cuffs": {
    "image_url": "https://oldschool.runescape.wiki/images/c/cc/Dark_tuxedo_cuffs.png?73103",
    "wiki_url": "https://oldschool.runescape.wiki/w/Dark_tuxedo_cuffs",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Diamond bracelet": {
    "image_url": "https://oldschool.runescape.wiki/images/c/c2/Diamond_bracelet.png?e2602",
    "wiki_url": "https://oldschool.runescape.wiki/w/Diamond_bracelet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Dragon gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/0/07/Dragon_gloves.png?8fa13",
    "wiki_url": "https://oldschool.runescape.wiki/w/Dragon_gloves",
    "stab_atk": "+9",
    "slash_atk": "+9",
    "crush_atk": "+9",
    "magic_atk": "+5",
    "ranged_atk": "+9",
    "stab_def": "+9",
    "slash_def": "+9",
    "crush_def": "+9",
    "magic_def": "+5",
    "ranged_def": "+9",
    "str_bonus": "+9",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Dragonstone bracelet": {
    "image_url": "https://oldschool.runescape.wiki/images/4/44/Dragonstone_bracelet.png?cc5f3",
    "wiki_url": "https://oldschool.runescape.wiki/w/Dragonstone_bracelet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Dragonstone gauntlets": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b3/Dragonstone_gauntlets.png?5eb13",
    "wiki_url": "https://oldschool.runescape.wiki/w/Dragonstone_gauntlets",
    "stab_atk": "+8",
    "slash_atk": "+8",
    "crush_atk": "+8",
    "magic_atk": "-4",
    "ranged_atk": "-3",
    "stab_def": "+8",
    "slash_def": "+8",
    "crush_def": "+8",
    "magic_def": "-4",
    "ranged_def": "+4",
    "str_bonus": "+4",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Elven gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/a/a0/Elven_gloves.png?c85b3",
    "wiki_url": "https://oldschool.runescape.wiki/w/Elven_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Emerald bracelet": {
    "image_url": "https://oldschool.runescape.wiki/images/e/e8/Emerald_bracelet.png?ef54e",
    "wiki_url": "https://oldschool.runescape.wiki/w/Emerald_bracelet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Expeditious bracelet": {
    "image_url": "https://oldschool.runescape.wiki/images/5/50/Expeditious_bracelet.png?b8cf0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Expeditious_bracelet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Expert mining gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/e/e0/Expert_mining_gloves.png?01f76",
    "wiki_url": "https://oldschool.runescape.wiki/w/Expert_mining_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ferocious gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/e/eb/Ferocious_gloves.png?97fe8",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ferocious_gloves",
    "stab_atk": "+16",
    "slash_atk": "+16",
    "crush_atk": "+16",
    "magic_atk": "-16",
    "ranged_atk": "-16",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+14",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Flamtaer bracelet": {
    "image_url": "https://oldschool.runescape.wiki/images/c/c4/Flamtaer_bracelet.png?96770",
    "wiki_url": "https://oldschool.runescape.wiki/w/Flamtaer_bracelet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Fremennik gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/7/72/Fremennik_gloves.png?c27d7",
    "wiki_url": "https://oldschool.runescape.wiki/w/Fremennik_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+2",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ghostly gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/d/d4/Ghostly_gloves.png?d2266",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ghostly_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+2",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+2",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Gilded d'hide vambraces": {
    "image_url": "https://oldschool.runescape.wiki/images/d/d2/Gilded_d%27hide_vambraces.png?fe558",
    "wiki_url": "https://oldschool.runescape.wiki/w/Gilded_d%27hide_vambraces",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-10",
    "ranged_atk": "+8",
    "stab_def": "+3",
    "slash_def": "+2",
    "crush_def": "+4",
    "magic_def": "+2",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Gloves of darkness": {
    "image_url": "https://oldschool.runescape.wiki/images/1/14/Gloves_of_darkness.png?caa5a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Gloves_of_darkness",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+3",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+3",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Gloves of silence": {
    "image_url": "https://oldschool.runescape.wiki/images/f/f0/Gloves_of_silence.png?caa5a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Gloves_of_silence",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+2",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Gold bracelet": {
    "image_url": "https://oldschool.runescape.wiki/images/3/34/Gold_bracelet.png?122dd",
    "wiki_url": "https://oldschool.runescape.wiki/w/Gold_bracelet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Goldsmith gauntlets": {
    "image_url": "https://oldschool.runescape.wiki/images/2/2f/Goldsmith_gauntlets.png?3d117",
    "wiki_url": "https://oldschool.runescape.wiki/w/Goldsmith_gauntlets",
    "stab_atk": "+2",
    "slash_atk": "+2",
    "crush_atk": "+2",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+8",
    "slash_def": "+9",
    "crush_def": "+7",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+2",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Graceful gloves#Agility_Arena": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b0/Graceful_gloves_%28Agility_Arena%29.png?99c22",
    "wiki_url": "https://oldschool.runescape.wiki/w/Graceful_gloves#Agility_Arena",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Graceful gloves#Arceuus": {
    "image_url": "https://oldschool.runescape.wiki/images/a/a7/Graceful_gloves_%28Arceuus%29.png?19135",
    "wiki_url": "https://oldschool.runescape.wiki/w/Graceful_gloves#Arceuus",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Graceful gloves#Hallowed": {
    "image_url": "https://oldschool.runescape.wiki/images/1/16/Graceful_gloves_%28Hallowed%29.png?99c22",
    "wiki_url": "https://oldschool.runescape.wiki/w/Graceful_gloves#Hallowed",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Graceful gloves#Hosidius": {
    "image_url": "https://oldschool.runescape.wiki/images/c/c1/Graceful_gloves_%28Hosidius%29.png?19135",
    "wiki_url": "https://oldschool.runescape.wiki/w/Graceful_gloves#Hosidius",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Graceful gloves#Kourend": {
    "image_url": "https://oldschool.runescape.wiki/images/6/6c/Graceful_gloves_%28Kourend%29.png?99c22",
    "wiki_url": "https://oldschool.runescape.wiki/w/Graceful_gloves#Kourend",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Graceful gloves#Lovakengj": {
    "image_url": "https://oldschool.runescape.wiki/images/e/e2/Graceful_gloves_%28Lovakengj%29.png?99c22",
    "wiki_url": "https://oldschool.runescape.wiki/w/Graceful_gloves#Lovakengj",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Graceful gloves#Piscarilius": {
    "image_url": "https://oldschool.runescape.wiki/images/7/76/Graceful_gloves_%28Piscarilius%29.png?99c22",
    "wiki_url": "https://oldschool.runescape.wiki/w/Graceful_gloves#Piscarilius",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Graceful gloves#Regular": {
    "image_url": "https://oldschool.runescape.wiki/images/6/64/Graceful_gloves.png?99c22",
    "wiki_url": "https://oldschool.runescape.wiki/w/Graceful_gloves#Regular",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Graceful gloves#Shayzien": {
    "image_url": "https://oldschool.runescape.wiki/images/b/be/Graceful_gloves_%28Shayzien%29.png?99c22",
    "wiki_url": "https://oldschool.runescape.wiki/w/Graceful_gloves#Shayzien",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Graceful gloves#Trailblazer": {
    "image_url": "https://oldschool.runescape.wiki/images/7/72/Graceful_gloves_%28Trailblazer%29.png?99c22",
    "wiki_url": "https://oldschool.runescape.wiki/w/Graceful_gloves#Trailblazer",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Granite gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/d/d5/Granite_gloves.png?fee90",
    "wiki_url": "https://oldschool.runescape.wiki/w/Granite_gloves",
    "stab_atk": "+5",
    "slash_atk": "+5",
    "crush_atk": "+9",
    "magic_atk": "-3",
    "ranged_atk": "-1",
    "stab_def": "+8",
    "slash_def": "+8",
    "crush_def": "+8",
    "magic_def": "-3",
    "ranged_def": "+5",
    "str_bonus": "+7",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Gravedigger gloves#During_event": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b2/Gravedigger_gloves.png?e75c0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Gravedigger_gloves#During_event",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Gravedigger gloves#Reward": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b2/Gravedigger_gloves.png?e75c0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Gravedigger_gloves#Reward",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Green d'hide vambraces": {
    "image_url": "https://oldschool.runescape.wiki/images/7/71/Green_d%27hide_vambraces.png?4e070",
    "wiki_url": "https://oldschool.runescape.wiki/w/Green_d%27hide_vambraces",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-10",
    "ranged_atk": "+8",
    "stab_def": "+3",
    "slash_def": "+2",
    "crush_def": "+4",
    "magic_def": "+2",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Green spiky vambraces": {
    "image_url": "https://oldschool.runescape.wiki/images/d/d9/Green_spiky_vambraces.png?e75c0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Green_spiky_vambraces",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-10",
    "ranged_atk": "+8",
    "stab_def": "+3",
    "slash_def": "+2",
    "crush_def": "+4",
    "magic_def": "+2",
    "ranged_def": "+0",
    "str_bonus": "+2",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Grey gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/9/9a/Grey_gloves.png?e75c0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Grey_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+2",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Guthix bracers": {
    "image_url": "https://oldschool.runescape.wiki/images/8/82/Guthix_bracers.png?290af",
    "wiki_url": "https://oldschool.runescape.wiki/w/Guthix_bracers",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-10",
    "ranged_atk": "+11",
    "stab_def": "+6",
    "slash_def": "+5",
    "crush_def": "+7",
    "magic_def": "+8",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+1"
  },
  "Ham gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/4/42/Ham_gloves.png?43cf2",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ham_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+2",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Hardleather gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/4/4b/Hardleather_gloves.png?bfea5",
    "wiki_url": "https://oldschool.runescape.wiki/w/Hardleather_gloves",
    "stab_atk": "+1",
    "slash_atk": "+1",
    "crush_atk": "+1",
    "magic_atk": "+1",
    "ranged_atk": "+1",
    "stab_def": "+1",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+1",
    "ranged_def": "+1",
    "str_bonus": "+1",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Holy wraps": {
    "image_url": "https://oldschool.runescape.wiki/images/d/d9/Holy_wraps.png?53fc0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Holy_wraps",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+3"
  },
  "Ice gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/8/83/Ice_gloves.png?7331d",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ice_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+3",
    "crush_def": "+4",
    "magic_def": "+0",
    "ranged_def": "+2",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Infinity gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/c/c2/Infinity_gloves.png?13f14",
    "wiki_url": "https://oldschool.runescape.wiki/w/Infinity_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+5",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+5",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Inoculation bracelet": {
    "image_url": "https://oldschool.runescape.wiki/images/5/5a/Inoculation_bracelet.png?13f14",
    "wiki_url": "https://oldschool.runescape.wiki/w/Inoculation_bracelet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Iron gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/2/24/Iron_gloves.png?e75c0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Iron_gloves",
    "stab_atk": "+3",
    "slash_atk": "+3",
    "crush_atk": "+3",
    "magic_atk": "+2",
    "ranged_atk": "+3",
    "stab_def": "+3",
    "slash_def": "+3",
    "crush_def": "+3",
    "magic_def": "+2",
    "ranged_def": "+3",
    "str_bonus": "+3",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Jade bracelet": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b4/Jade_bracelet.png?c27a4",
    "wiki_url": "https://oldschool.runescape.wiki/w/Jade_bracelet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Karamja gloves 1": {
    "image_url": "https://oldschool.runescape.wiki/images/f/fb/Karamja_gloves_1.png?863e0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Karamja_gloves_1",
    "stab_atk": "+1",
    "slash_atk": "+1",
    "crush_atk": "+1",
    "magic_atk": "+1",
    "ranged_atk": "+1",
    "stab_def": "+1",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+1",
    "ranged_def": "+1",
    "str_bonus": "+1",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Karamja gloves 2": {
    "image_url": "https://oldschool.runescape.wiki/images/6/6f/Karamja_gloves_2.png?863e0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Karamja_gloves_2",
    "stab_atk": "+1",
    "slash_atk": "+1",
    "crush_atk": "+1",
    "magic_atk": "+1",
    "ranged_atk": "+1",
    "stab_def": "+1",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+1",
    "ranged_def": "+1",
    "str_bonus": "+1",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Karamja gloves 3": {
    "image_url": "https://oldschool.runescape.wiki/images/0/08/Karamja_gloves_3.png?863e0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Karamja_gloves_3",
    "stab_atk": "+1",
    "slash_atk": "+1",
    "crush_atk": "+1",
    "magic_atk": "+1",
    "ranged_atk": "+1",
    "stab_def": "+1",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+1",
    "ranged_def": "+1",
    "str_bonus": "+1",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Karamja gloves 4": {
    "image_url": "https://oldschool.runescape.wiki/images/7/71/Karamja_gloves_4.png?863e0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Karamja_gloves_4",
    "stab_atk": "+1",
    "slash_atk": "+1",
    "crush_atk": "+1",
    "magic_atk": "+1",
    "ranged_atk": "+1",
    "stab_def": "+1",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+1",
    "ranged_def": "+1",
    "str_bonus": "+1",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Klank's gauntlets": {
    "image_url": "https://oldschool.runescape.wiki/images/e/ed/Klank%27s_gauntlets.png?ec129",
    "wiki_url": "https://oldschool.runescape.wiki/w/Klank%27s_gauntlets",
    "stab_atk": "+2",
    "slash_atk": "+2",
    "crush_atk": "+2",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+8",
    "slash_def": "+9",
    "crush_def": "+7",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+2",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Leather gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/9/95/Leather_gloves.png?6592f",
    "wiki_url": "https://oldschool.runescape.wiki/w/Leather_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+2",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Leather vambraces": {
    "image_url": "https://oldschool.runescape.wiki/images/a/a0/Leather_vambraces.png?01ae1",
    "wiki_url": "https://oldschool.runescape.wiki/w/Leather_vambraces",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+4",
    "stab_def": "+2",
    "slash_def": "+2",
    "crush_def": "+1",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Light tuxedo cuffs": {
    "image_url": "https://oldschool.runescape.wiki/images/9/92/Light_tuxedo_cuffs.png?01ae1",
    "wiki_url": "https://oldschool.runescape.wiki/w/Light_tuxedo_cuffs",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Lunar gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/1/1d/Lunar_gloves.png?8bd5a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Lunar_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+4",
    "ranged_atk": "-1",
    "stab_def": "+2",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+2",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Mime gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/f/fb/Mime_gloves.png?ed6d0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Mime_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Mining gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/9/96/Mining_gloves.png?ccf02",
    "wiki_url": "https://oldschool.runescape.wiki/w/Mining_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Mithril gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/9/98/Mithril_gloves.png?71f7a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Mithril_gloves",
    "stab_atk": "+6",
    "slash_atk": "+6",
    "crush_atk": "+6",
    "magic_atk": "+3",
    "ranged_atk": "+6",
    "stab_def": "+6",
    "slash_def": "+6",
    "crush_def": "+6",
    "magic_def": "+3",
    "ranged_def": "+6",
    "str_bonus": "+6",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Moonclan gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/8/8c/Moonclan_gloves.png?8cc7e",
    "wiki_url": "https://oldschool.runescape.wiki/w/Moonclan_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+2",
    "ranged_atk": "-5",
    "stab_def": "+2",
    "slash_def": "+2",
    "crush_def": "+2",
    "magic_def": "+2",
    "ranged_def": "-5",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Mourner gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/6/67/Mourner_gloves.png?7027d",
    "wiki_url": "https://oldschool.runescape.wiki/w/Mourner_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+2",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Mummy's hands": {
    "image_url": "https://oldschool.runescape.wiki/images/4/4c/Mummy%27s_hands.png?7027d",
    "wiki_url": "https://oldschool.runescape.wiki/w/Mummy%27s_hands",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Mystic gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b0/Mystic_gloves.png?246bf",
    "wiki_url": "https://oldschool.runescape.wiki/w/Mystic_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+3",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+3",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Mystic gloves (dark)": {
    "image_url": "https://oldschool.runescape.wiki/images/0/0d/Mystic_gloves_%28dark%29.png?db23d",
    "wiki_url": "https://oldschool.runescape.wiki/w/Mystic_gloves_(dark)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+3",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+3",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Mystic gloves (dusk)": {
    "image_url": "https://oldschool.runescape.wiki/images/e/e8/Mystic_gloves_%28dusk%29.png?8bd5a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Mystic_gloves_(dusk)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+3",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+3",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Mystic gloves (light)": {
    "image_url": "https://oldschool.runescape.wiki/images/a/ae/Mystic_gloves_%28light%29.png?246bf",
    "wiki_url": "https://oldschool.runescape.wiki/w/Mystic_gloves_(light)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+3",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+3",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Onyx bracelet": {
    "image_url": "https://oldschool.runescape.wiki/images/9/90/Onyx_bracelet.png?4068d",
    "wiki_url": "https://oldschool.runescape.wiki/w/Onyx_bracelet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Opal bracelet": {
    "image_url": "https://oldschool.runescape.wiki/images/7/7f/Opal_bracelet.png?8bdb9",
    "wiki_url": "https://oldschool.runescape.wiki/w/Opal_bracelet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ornate gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/1/12/Ornate_gloves.png?de02e",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ornate_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+2",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Penance gloves#Worn": {
    "image_url": "https://oldschool.runescape.wiki/images/3/34/Penance_gloves.png?e3d63",
    "wiki_url": "https://oldschool.runescape.wiki/w/Penance_gloves#Worn",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+3",
    "crush_def": "+4",
    "magic_def": "+0",
    "ranged_def": "+2",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Pirate's hook": {
    "image_url": "https://oldschool.runescape.wiki/images/f/ff/Pirate%27s_hook.png?f976b",
    "wiki_url": "https://oldschool.runescape.wiki/w/Pirate%27s_hook",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+1",
    "slash_def": "+5",
    "crush_def": "+3",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Purple gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/5/54/Purple_gloves.png?d9f1b",
    "wiki_url": "https://oldschool.runescape.wiki/w/Purple_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+2",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ranger gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/e/ec/Ranger_gloves.png?095ed",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ranger_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-10",
    "ranged_atk": "+11",
    "stab_def": "+1",
    "slash_def": "+2",
    "crush_def": "+1",
    "magic_def": "+2",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Red d'hide vambraces": {
    "image_url": "https://oldschool.runescape.wiki/images/f/f9/Red_d%27hide_vambraces.png?77caa",
    "wiki_url": "https://oldschool.runescape.wiki/w/Red_d%27hide_vambraces",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-10",
    "ranged_atk": "+10",
    "stab_def": "+5",
    "slash_def": "+4",
    "crush_def": "+6",
    "magic_def": "+6",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Red gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/7/7f/Red_gloves.png?cb76b",
    "wiki_url": "https://oldschool.runescape.wiki/w/Red_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+2",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Red spiky vambraces": {
    "image_url": "https://oldschool.runescape.wiki/images/e/eb/Red_spiky_vambraces.png?db71c",
    "wiki_url": "https://oldschool.runescape.wiki/w/Red_spiky_vambraces",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-10",
    "ranged_atk": "+10",
    "stab_def": "+5",
    "slash_def": "+4",
    "crush_def": "+6",
    "magic_def": "+6",
    "ranged_def": "+0",
    "str_bonus": "+2",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Regen bracelet": {
    "image_url": "https://oldschool.runescape.wiki/images/5/54/Regen_bracelet.png?2e2e3",
    "wiki_url": "https://oldschool.runescape.wiki/w/Regen_bracelet",
    "stab_atk": "+8",
    "slash_atk": "+8",
    "crush_atk": "+8",
    "magic_atk": "+3",
    "ranged_atk": "+7",
    "stab_def": "+6",
    "slash_def": "+6",
    "crush_def": "+6",
    "magic_def": "+3",
    "ranged_def": "+6",
    "str_bonus": "+7",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Rock-shell gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/3/39/Rock-shell_gloves.png?c76a5",
    "wiki_url": "https://oldschool.runescape.wiki/w/Rock-shell_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+2",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Rogue gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b1/Rogue_gloves.png?43f24",
    "wiki_url": "https://oldschool.runescape.wiki/w/Rogue_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+2",
    "slash_def": "+2",
    "crush_def": "+2",
    "magic_def": "+2",
    "ranged_def": "+2",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ruby bracelet": {
    "image_url": "https://oldschool.runescape.wiki/images/f/f3/Ruby_bracelet.png?625fb",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ruby_bracelet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Rune gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/d/d8/Rune_gloves.png?ce07d",
    "wiki_url": "https://oldschool.runescape.wiki/w/Rune_gloves",
    "stab_atk": "+8",
    "slash_atk": "+8",
    "crush_atk": "+8",
    "magic_atk": "+4",
    "ranged_atk": "+8",
    "stab_def": "+8",
    "slash_def": "+8",
    "crush_def": "+8",
    "magic_def": "+4",
    "ranged_def": "+8",
    "str_bonus": "+8",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Samurai gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b0/Samurai_gloves.png?28ea5",
    "wiki_url": "https://oldschool.runescape.wiki/w/Samurai_gloves",
    "stab_atk": "+2",
    "slash_atk": "+2",
    "crush_atk": "+2",
    "magic_atk": "+2",
    "ranged_atk": "+2",
    "stab_def": "+3",
    "slash_def": "+3",
    "crush_def": "+3",
    "magic_def": "+3",
    "ranged_def": "+3",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Santa gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/5/54/Santa_gloves.png?dcaa9",
    "wiki_url": "https://oldschool.runescape.wiki/w/Santa_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Sapphire bracelet": {
    "image_url": "https://oldschool.runescape.wiki/images/0/0a/Sapphire_bracelet.png?c4e91",
    "wiki_url": "https://oldschool.runescape.wiki/w/Sapphire_bracelet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Saradomin bracers": {
    "image_url": "https://oldschool.runescape.wiki/images/9/98/Saradomin_bracers.png?0ee99",
    "wiki_url": "https://oldschool.runescape.wiki/w/Saradomin_bracers",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-10",
    "ranged_atk": "+11",
    "stab_def": "+6",
    "slash_def": "+5",
    "crush_def": "+7",
    "magic_def": "+8",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+1"
  },
  "Shayzien gloves (1)": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b6/Shayzien_gloves_%281%29.png?f410d",
    "wiki_url": "https://oldschool.runescape.wiki/w/Shayzien_gloves_(1)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-1",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+1",
    "magic_def": "-1",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Shayzien gloves (2)": {
    "image_url": "https://oldschool.runescape.wiki/images/9/9e/Shayzien_gloves_%282%29.png?847d4",
    "wiki_url": "https://oldschool.runescape.wiki/w/Shayzien_gloves_(2)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+1",
    "magic_atk": "-1",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+1",
    "magic_def": "-1",
    "ranged_def": "+0",
    "str_bonus": "+1",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Shayzien gloves (3)": {
    "image_url": "https://oldschool.runescape.wiki/images/3/32/Shayzien_gloves_%283%29.png?4b960",
    "wiki_url": "https://oldschool.runescape.wiki/w/Shayzien_gloves_(3)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+2",
    "magic_atk": "-1",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+1",
    "magic_def": "-1",
    "ranged_def": "+0",
    "str_bonus": "+2",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Shayzien gloves (4)": {
    "image_url": "https://oldschool.runescape.wiki/images/9/9a/Shayzien_gloves_%284%29.png?4b960",
    "wiki_url": "https://oldschool.runescape.wiki/w/Shayzien_gloves_(4)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+2",
    "magic_atk": "-1",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+2",
    "magic_def": "-1",
    "ranged_def": "+1",
    "str_bonus": "+2",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Shayzien gloves (5)": {
    "image_url": "https://oldschool.runescape.wiki/images/b/ba/Shayzien_gloves_%285%29.png?4b960",
    "wiki_url": "https://oldschool.runescape.wiki/w/Shayzien_gloves_(5)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+2",
    "magic_atk": "-1",
    "ranged_atk": "+6",
    "stab_def": "+0",
    "slash_def": "+2",
    "crush_def": "+3",
    "magic_def": "-1",
    "ranged_def": "+2",
    "str_bonus": "+3",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Skeletal gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/a/ab/Skeletal_gloves.png?0df0a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Skeletal_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+2",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Skeleton gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/9/90/Skeleton_gloves.png?0df0a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Skeleton_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Slayer gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/8/8f/Slayer_gloves.png?1d1f2",
    "wiki_url": "https://oldschool.runescape.wiki/w/Slayer_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+4",
    "slash_def": "+5",
    "crush_def": "+3",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Snakeskin vambraces": {
    "image_url": "https://oldschool.runescape.wiki/images/1/19/Snakeskin_vambraces.png?44c1f",
    "wiki_url": "https://oldschool.runescape.wiki/w/Snakeskin_vambraces",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-5",
    "ranged_atk": "+6",
    "stab_def": "+2",
    "slash_def": "+2",
    "crush_def": "+2",
    "magic_def": "+1",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Snow imp costume gloves#During_event": {
    "image_url": "https://oldschool.runescape.wiki/images/8/8f/Snow_imp_costume_gloves.png?d8c27",
    "wiki_url": "https://oldschool.runescape.wiki/w/Snow_imp_costume_gloves#During_event",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Snow imp costume gloves#Reward": {
    "image_url": "https://oldschool.runescape.wiki/images/8/8f/Snow_imp_costume_gloves.png?d8c27",
    "wiki_url": "https://oldschool.runescape.wiki/w/Snow_imp_costume_gloves#Reward",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Spiky vambraces": {
    "image_url": "https://oldschool.runescape.wiki/images/0/02/Spiky_vambraces.png?848ff",
    "wiki_url": "https://oldschool.runescape.wiki/w/Spiky_vambraces",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+4",
    "stab_def": "+2",
    "slash_def": "+2",
    "crush_def": "+1",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+2",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Spined gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/7/7a/Spined_gloves.png?462fd",
    "wiki_url": "https://oldschool.runescape.wiki/w/Spined_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+2",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Splitbark gauntlets": {
    "image_url": "https://oldschool.runescape.wiki/images/1/12/Splitbark_gauntlets.png?e8969",
    "wiki_url": "https://oldschool.runescape.wiki/w/Splitbark_gauntlets",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+2",
    "ranged_atk": "-1",
    "stab_def": "+3",
    "slash_def": "+2",
    "crush_def": "+4",
    "magic_def": "+2",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Spookier gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/7/7b/Spookier_gloves.png?e8969",
    "wiki_url": "https://oldschool.runescape.wiki/w/Spookier_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Spooky gloves#Reward": {
    "image_url": "https://oldschool.runescape.wiki/images/5/54/Spooky_gloves.png?e8969",
    "wiki_url": "https://oldschool.runescape.wiki/w/Spooky_gloves#Reward",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Steel gauntlets": {
    "image_url": "https://oldschool.runescape.wiki/images/3/37/Steel_gauntlets.png?3203e",
    "wiki_url": "https://oldschool.runescape.wiki/w/Steel_gauntlets",
    "stab_atk": "+2",
    "slash_atk": "+2",
    "crush_atk": "+2",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+8",
    "slash_def": "+9",
    "crush_def": "+7",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+2",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Steel gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/5/54/Steel_gloves.png?3203e",
    "wiki_url": "https://oldschool.runescape.wiki/w/Steel_gloves",
    "stab_atk": "+4",
    "slash_atk": "+4",
    "crush_atk": "+4",
    "magic_atk": "+2",
    "ranged_atk": "+4",
    "stab_def": "+4",
    "slash_def": "+4",
    "crush_def": "+4",
    "magic_def": "+2",
    "ranged_def": "+4",
    "str_bonus": "+4",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Superior mining gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/f/fa/Superior_mining_gloves.png?9f3ef",
    "wiki_url": "https://oldschool.runescape.wiki/w/Superior_mining_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Swampbark gauntlets": {
    "image_url": "https://oldschool.runescape.wiki/images/1/1e/Swampbark_gauntlets.png?9f3ef",
    "wiki_url": "https://oldschool.runescape.wiki/w/Swampbark_gauntlets",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+3",
    "ranged_atk": "+0",
    "stab_def": "+4",
    "slash_def": "+3",
    "crush_def": "+5",
    "magic_def": "+4",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Teal gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/4/4a/Teal_gloves.png?04f28",
    "wiki_url": "https://oldschool.runescape.wiki/w/Teal_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+2",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Topaz bracelet": {
    "image_url": "https://oldschool.runescape.wiki/images/c/cb/Topaz_bracelet.png?b77a4",
    "wiki_url": "https://oldschool.runescape.wiki/w/Topaz_bracelet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Tormented bracelet": {
    "image_url": "https://oldschool.runescape.wiki/images/4/45/Tormented_bracelet.png?c9227",
    "wiki_url": "https://oldschool.runescape.wiki/w/Tormented_bracelet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+10",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+5%",
    "prayer": "+2"
  },
  "Tormented bracelet (or)": {
    "image_url": "https://oldschool.runescape.wiki/images/d/d2/Tormented_bracelet_%28or%29.png?942ca",
    "wiki_url": "https://oldschool.runescape.wiki/w/Tormented_bracelet_(or)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+10",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+5%",
    "prayer": "+2"
  },
  "Villager armband (blue)": {
    "image_url": "https://oldschool.runescape.wiki/images/2/2c/Villager_armband_%28blue%29.png?19779",
    "wiki_url": "https://oldschool.runescape.wiki/w/Villager_armband_(blue)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Villager armband (brown)": {
    "image_url": "https://oldschool.runescape.wiki/images/c/c0/Villager_armband_%28brown%29.png?4afbb",
    "wiki_url": "https://oldschool.runescape.wiki/w/Villager_armband_(brown)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Villager armband (pink)": {
    "image_url": "https://oldschool.runescape.wiki/images/2/2f/Villager_armband_%28pink%29.png?b7686",
    "wiki_url": "https://oldschool.runescape.wiki/w/Villager_armband_(pink)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Villager armband (yellow)": {
    "image_url": "https://oldschool.runescape.wiki/images/8/84/Villager_armband_%28yellow%29.png?4afbb",
    "wiki_url": "https://oldschool.runescape.wiki/w/Villager_armband_(yellow)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Void knight gloves#Broken": {
    "image_url": "https://oldschool.runescape.wiki/images/e/e9/Void_knight_gloves_%28broken%29.png?4afbb",
    "wiki_url": "https://oldschool.runescape.wiki/w/Void_knight_gloves#Broken",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+6",
    "slash_def": "+6",
    "crush_def": "+6",
    "magic_def": "+4",
    "ranged_def": "+6",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Void knight gloves#Locked": {
    "image_url": "https://oldschool.runescape.wiki/images/9/91/Void_knight_gloves.png?75a26",
    "wiki_url": "https://oldschool.runescape.wiki/w/Void_knight_gloves#Locked",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+6",
    "slash_def": "+6",
    "crush_def": "+6",
    "magic_def": "+4",
    "ranged_def": "+6",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Void knight gloves#Normal": {
    "image_url": "https://oldschool.runescape.wiki/images/9/91/Void_knight_gloves.png?75a26",
    "wiki_url": "https://oldschool.runescape.wiki/w/Void_knight_gloves#Normal",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+6",
    "slash_def": "+6",
    "crush_def": "+6",
    "magic_def": "+4",
    "ranged_def": "+6",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Warm gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/8/8b/Warm_gloves.png?43659",
    "wiki_url": "https://oldschool.runescape.wiki/w/Warm_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "White gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/4/42/White_gloves.png?76afe",
    "wiki_url": "https://oldschool.runescape.wiki/w/White_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+2",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+1"
  },
  "Yellow gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/7/73/Yellow_gloves.png?5e59e",
    "wiki_url": "https://oldschool.runescape.wiki/w/Yellow_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+1",
    "crush_def": "+2",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Zamorak bracers": {
    "image_url": "https://oldschool.runescape.wiki/images/0/0a/Zamorak_bracers.png?1bd0f",
    "wiki_url": "https://oldschool.runescape.wiki/w/Zamorak_bracers",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "-10",
    "ranged_atk": "+11",
    "stab_def": "+6",
    "slash_def": "+5",
    "crush_def": "+7",
    "magic_def": "+8",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+1"
  },
  "Zenyte bracelet": {
    "image_url": "https://oldschool.runescape.wiki/images/e/e7/Zenyte_bracelet.png?8abb8",
    "wiki_url": "https://oldschool.runescape.wiki/w/Zenyte_bracelet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Zombie gloves": {
    "image_url": "https://oldschool.runescape.wiki/images/3/3f/Zombie_gloves.png?8abb8",
    "wiki_url": "https://oldschool.runescape.wiki/w/Zombie_gloves",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  }
}