window.equipment.neck = {
  "10th squad sigil": {
    "image_url": "https://oldschool.runescape.wiki/images/e/ea/10th_squad_sigil.png?3e370",
    "wiki_url": "https://oldschool.runescape.wiki/w/10th_squad_sigil",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "20th anniversary necklace": {
    "image_url": "https://oldschool.runescape.wiki/images/1/1f/20th_anniversary_necklace.png?eeb0c",
    "wiki_url": "https://oldschool.runescape.wiki/w/20th_anniversary_necklace",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "3rd age amulet": {
    "image_url": "https://oldschool.runescape.wiki/images/c/c1/3rd_age_amulet.png?6fa46",
    "wiki_url": "https://oldschool.runescape.wiki/w/3rd_age_amulet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+15",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+10",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Amulet of accuracy": {
    "image_url": "https://oldschool.runescape.wiki/images/1/1b/Amulet_of_accuracy.png?d8729",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_accuracy",
    "stab_atk": "+4",
    "slash_atk": "+4",
    "crush_atk": "+4",
    "magic_atk": "+4",
    "ranged_atk": "+4",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Amulet of avarice": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b6/Amulet_of_avarice.png?248b4",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_avarice",
    "stab_atk": "+10",
    "slash_atk": "+10",
    "crush_atk": "+10",
    "magic_atk": "+10",
    "ranged_atk": "+10",
    "stab_def": "+3",
    "slash_def": "+3",
    "crush_def": "+3",
    "magic_def": "+3",
    "ranged_def": "+3",
    "str_bonus": "+6",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+3"
  },
  "Amulet of blood fury": {
    "image_url": "https://oldschool.runescape.wiki/images/7/72/Amulet_of_blood_fury.png?ec289",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_blood_fury",
    "stab_atk": "+10",
    "slash_atk": "+10",
    "crush_atk": "+10",
    "magic_atk": "+10",
    "ranged_atk": "+10",
    "stab_def": "+15",
    "slash_def": "+15",
    "crush_def": "+15",
    "magic_def": "+15",
    "ranged_def": "+15",
    "str_bonus": "+8",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+5"
  },
  "Amulet of bounty": {
    "image_url": "https://oldschool.runescape.wiki/images/8/89/Amulet_of_bounty.png?ec289",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_bounty",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Amulet of chemistry": {
    "image_url": "https://oldschool.runescape.wiki/images/a/af/Amulet_of_chemistry.png?248b4",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_chemistry",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Amulet of defence": {
    "image_url": "https://oldschool.runescape.wiki/images/4/4e/Amulet_of_defence.png?248b4",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_defence",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+7",
    "slash_def": "+7",
    "crush_def": "+7",
    "magic_def": "+7",
    "ranged_def": "+7",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Amulet of defence (t)": {
    "image_url": "https://oldschool.runescape.wiki/images/6/6a/Amulet_of_defence_%28t%29.png?d8729",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_defence_(t)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+7",
    "slash_def": "+7",
    "crush_def": "+7",
    "magic_def": "+7",
    "ranged_def": "+7",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Amulet of eternal glory": {
    "image_url": "https://oldschool.runescape.wiki/images/2/24/Amulet_of_eternal_glory.png?248b4",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_eternal_glory",
    "stab_atk": "+10",
    "slash_atk": "+10",
    "crush_atk": "+10",
    "magic_atk": "+10",
    "ranged_atk": "+10",
    "stab_def": "+3",
    "slash_def": "+3",
    "crush_def": "+3",
    "magic_def": "+3",
    "ranged_def": "+3",
    "str_bonus": "+6",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+3"
  },
  "Amulet of fury": {
    "image_url": "https://oldschool.runescape.wiki/images/0/02/Amulet_of_fury.png?248b4",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_fury",
    "stab_atk": "+10",
    "slash_atk": "+10",
    "crush_atk": "+10",
    "magic_atk": "+10",
    "ranged_atk": "+10",
    "stab_def": "+15",
    "slash_def": "+15",
    "crush_def": "+15",
    "magic_def": "+15",
    "ranged_def": "+15",
    "str_bonus": "+8",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+5"
  },
  "Amulet of fury (Last Man Standing)": {
    "image_url": "https://oldschool.runescape.wiki/images/9/99/Amulet_of_fury_%28Last_Man_Standing%29.png?248b4",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_fury_(Last_Man_Standing)",
    "stab_atk": "+10",
    "slash_atk": "+10",
    "crush_atk": "+10",
    "magic_atk": "+10",
    "ranged_atk": "+10",
    "stab_def": "+15",
    "slash_def": "+15",
    "crush_def": "+15",
    "magic_def": "+15",
    "ranged_def": "+15",
    "str_bonus": "+8",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+5"
  },
  "Amulet of fury (or)": {
    "image_url": "https://oldschool.runescape.wiki/images/4/42/Amulet_of_fury_%28or%29.png?d8729",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_fury_(or)",
    "stab_atk": "+10",
    "slash_atk": "+10",
    "crush_atk": "+10",
    "magic_atk": "+10",
    "ranged_atk": "+10",
    "stab_def": "+15",
    "slash_def": "+15",
    "crush_def": "+15",
    "magic_def": "+15",
    "ranged_def": "+15",
    "str_bonus": "+8",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+5"
  },
  "Amulet of glory (Last Man Standing)": {
    "image_url": "https://oldschool.runescape.wiki/images/c/cb/Amulet_of_glory_%28Last_Man_Standing%29.png?ec289",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_glory_(Last_Man_Standing)",
    "stab_atk": "+10",
    "slash_atk": "+10",
    "crush_atk": "+10",
    "magic_atk": "+10",
    "ranged_atk": "+10",
    "stab_def": "+3",
    "slash_def": "+3",
    "crush_def": "+3",
    "magic_def": "+3",
    "ranged_def": "+3",
    "str_bonus": "+6",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+3"
  },
  "Amulet of glory (t)#(t1)": {
    "image_url": "https://oldschool.runescape.wiki/images/0/0f/Amulet_of_glory_%28t1%29.png?4470c",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_glory_(t)#(t1)",
    "stab_atk": "+10",
    "slash_atk": "+10",
    "crush_atk": "+10",
    "magic_atk": "+10",
    "ranged_atk": "+10",
    "stab_def": "+3",
    "slash_def": "+3",
    "crush_def": "+3",
    "magic_def": "+3",
    "ranged_def": "+3",
    "str_bonus": "+6",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+3"
  },
  "Amulet of glory (t)#(t2)": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b0/Amulet_of_glory_%28t2%29.png?4470c",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_glory_(t)#(t2)",
    "stab_atk": "+10",
    "slash_atk": "+10",
    "crush_atk": "+10",
    "magic_atk": "+10",
    "ranged_atk": "+10",
    "stab_def": "+3",
    "slash_def": "+3",
    "crush_def": "+3",
    "magic_def": "+3",
    "ranged_def": "+3",
    "str_bonus": "+6",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+3"
  },
  "Amulet of glory (t)#(t3)": {
    "image_url": "https://oldschool.runescape.wiki/images/3/3d/Amulet_of_glory_%28t3%29.png?4470c",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_glory_(t)#(t3)",
    "stab_atk": "+10",
    "slash_atk": "+10",
    "crush_atk": "+10",
    "magic_atk": "+10",
    "ranged_atk": "+10",
    "stab_def": "+3",
    "slash_def": "+3",
    "crush_def": "+3",
    "magic_def": "+3",
    "ranged_def": "+3",
    "str_bonus": "+6",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+3"
  },
  "Amulet of glory (t)#(t4)": {
    "image_url": "https://oldschool.runescape.wiki/images/d/d1/Amulet_of_glory_%28t4%29.png?4470c",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_glory_(t)#(t4)",
    "stab_atk": "+10",
    "slash_atk": "+10",
    "crush_atk": "+10",
    "magic_atk": "+10",
    "ranged_atk": "+10",
    "stab_def": "+3",
    "slash_def": "+3",
    "crush_def": "+3",
    "magic_def": "+3",
    "ranged_def": "+3",
    "str_bonus": "+6",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+3"
  },
  "Amulet of glory (t)#(t5)": {
    "image_url": "https://oldschool.runescape.wiki/images/1/19/Amulet_of_glory_%28t5%29.png?4470c",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_glory_(t)#(t5)",
    "stab_atk": "+10",
    "slash_atk": "+10",
    "crush_atk": "+10",
    "magic_atk": "+10",
    "ranged_atk": "+10",
    "stab_def": "+3",
    "slash_def": "+3",
    "crush_def": "+3",
    "magic_def": "+3",
    "ranged_def": "+3",
    "str_bonus": "+6",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+3"
  },
  "Amulet of glory (t)#(t6)": {
    "image_url": "https://oldschool.runescape.wiki/images/3/30/Amulet_of_glory_%28t6%29.png?4470c",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_glory_(t)#(t6)",
    "stab_atk": "+10",
    "slash_atk": "+10",
    "crush_atk": "+10",
    "magic_atk": "+10",
    "ranged_atk": "+10",
    "stab_def": "+3",
    "slash_def": "+3",
    "crush_def": "+3",
    "magic_def": "+3",
    "ranged_def": "+3",
    "str_bonus": "+6",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+3"
  },
  "Amulet of glory (t)#Uncharged": {
    "image_url": "https://oldschool.runescape.wiki/images/0/0a/Amulet_of_glory_%28t%29_%28uncharged%29.png?248b4",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_glory_(t)#Uncharged",
    "stab_atk": "+10",
    "slash_atk": "+10",
    "crush_atk": "+10",
    "magic_atk": "+10",
    "ranged_atk": "+10",
    "stab_def": "+3",
    "slash_def": "+3",
    "crush_def": "+3",
    "magic_def": "+3",
    "ranged_def": "+3",
    "str_bonus": "+6",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+3"
  },
  "Amulet of glory#(1)": {
    "image_url": "https://oldschool.runescape.wiki/images/2/2d/Amulet_of_glory%281%29.png?45b61",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_glory#(1)",
    "stab_atk": "+10",
    "slash_atk": "+10",
    "crush_atk": "+10",
    "magic_atk": "+10",
    "ranged_atk": "+10",
    "stab_def": "+3",
    "slash_def": "+3",
    "crush_def": "+3",
    "magic_def": "+3",
    "ranged_def": "+3",
    "str_bonus": "+6",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+3"
  },
  "Amulet of glory#(2)": {
    "image_url": "https://oldschool.runescape.wiki/images/f/f2/Amulet_of_glory%282%29.png?45b61",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_glory#(2)",
    "stab_atk": "+10",
    "slash_atk": "+10",
    "crush_atk": "+10",
    "magic_atk": "+10",
    "ranged_atk": "+10",
    "stab_def": "+3",
    "slash_def": "+3",
    "crush_def": "+3",
    "magic_def": "+3",
    "ranged_def": "+3",
    "str_bonus": "+6",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+3"
  },
  "Amulet of glory#(3)": {
    "image_url": "https://oldschool.runescape.wiki/images/a/af/Amulet_of_glory%283%29.png?45b61",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_glory#(3)",
    "stab_atk": "+10",
    "slash_atk": "+10",
    "crush_atk": "+10",
    "magic_atk": "+10",
    "ranged_atk": "+10",
    "stab_def": "+3",
    "slash_def": "+3",
    "crush_def": "+3",
    "magic_def": "+3",
    "ranged_def": "+3",
    "str_bonus": "+6",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+3"
  },
  "Amulet of glory#(4)": {
    "image_url": "https://oldschool.runescape.wiki/images/f/f0/Amulet_of_glory%284%29.png?15de7",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_glory#(4)",
    "stab_atk": "+10",
    "slash_atk": "+10",
    "crush_atk": "+10",
    "magic_atk": "+10",
    "ranged_atk": "+10",
    "stab_def": "+3",
    "slash_def": "+3",
    "crush_def": "+3",
    "magic_def": "+3",
    "ranged_def": "+3",
    "str_bonus": "+6",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+3"
  },
  "Amulet of glory#(5)": {
    "image_url": "https://oldschool.runescape.wiki/images/3/39/Amulet_of_glory%285%29.png?45b61",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_glory#(5)",
    "stab_atk": "+10",
    "slash_atk": "+10",
    "crush_atk": "+10",
    "magic_atk": "+10",
    "ranged_atk": "+10",
    "stab_def": "+3",
    "slash_def": "+3",
    "crush_def": "+3",
    "magic_def": "+3",
    "ranged_def": "+3",
    "str_bonus": "+6",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+3"
  },
  "Amulet of glory#(6)": {
    "image_url": "https://oldschool.runescape.wiki/images/f/f8/Amulet_of_glory%286%29.png?45b61",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_glory#(6)",
    "stab_atk": "+10",
    "slash_atk": "+10",
    "crush_atk": "+10",
    "magic_atk": "+10",
    "ranged_atk": "+10",
    "stab_def": "+3",
    "slash_def": "+3",
    "crush_def": "+3",
    "magic_def": "+3",
    "ranged_def": "+3",
    "str_bonus": "+6",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+3"
  },
  "Amulet of glory#Uncharged": {
    "image_url": "https://oldschool.runescape.wiki/images/c/cd/Amulet_of_glory.png?ec289",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_glory#Uncharged",
    "stab_atk": "+10",
    "slash_atk": "+10",
    "crush_atk": "+10",
    "magic_atk": "+10",
    "ranged_atk": "+10",
    "stab_def": "+3",
    "slash_def": "+3",
    "crush_def": "+3",
    "magic_def": "+3",
    "ranged_def": "+3",
    "str_bonus": "+6",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+3"
  },
  "Amulet of magic": {
    "image_url": "https://oldschool.runescape.wiki/images/b/bf/Amulet_of_magic.png?15de7",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_magic",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+10",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Amulet of magic (t)": {
    "image_url": "https://oldschool.runescape.wiki/images/e/ee/Amulet_of_magic_%28t%29.png?ec289",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_magic_(t)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+10",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Amulet of nature": {
    "image_url": "https://oldschool.runescape.wiki/images/2/2e/Amulet_of_nature.png?8d9e1",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_nature",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Amulet of power": {
    "image_url": "https://oldschool.runescape.wiki/images/1/14/Amulet_of_power.png?248b4",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_power",
    "stab_atk": "+6",
    "slash_atk": "+6",
    "crush_atk": "+6",
    "magic_atk": "+6",
    "ranged_atk": "+6",
    "stab_def": "+6",
    "slash_def": "+6",
    "crush_def": "+6",
    "magic_def": "+6",
    "ranged_def": "+6",
    "str_bonus": "+6",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+1"
  },
  "Amulet of power (Last Man Standing)": {
    "image_url": "https://oldschool.runescape.wiki/images/a/ae/Amulet_of_power_%28Last_Man_Standing%29.png?05955",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_power_(Last_Man_Standing)",
    "stab_atk": "+6",
    "slash_atk": "+6",
    "crush_atk": "+6",
    "magic_atk": "+6",
    "ranged_atk": "+6",
    "stab_def": "+6",
    "slash_def": "+6",
    "crush_def": "+6",
    "magic_def": "+6",
    "ranged_def": "+6",
    "str_bonus": "+6",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+1"
  },
  "Amulet of power (t)": {
    "image_url": "https://oldschool.runescape.wiki/images/7/77/Amulet_of_power_%28t%29.png?15de7",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_power_(t)",
    "stab_atk": "+6",
    "slash_atk": "+6",
    "crush_atk": "+6",
    "magic_atk": "+6",
    "ranged_atk": "+6",
    "stab_def": "+6",
    "slash_def": "+6",
    "crush_def": "+6",
    "magic_def": "+6",
    "ranged_def": "+6",
    "str_bonus": "+6",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+1"
  },
  "Amulet of strength": {
    "image_url": "https://oldschool.runescape.wiki/images/f/fb/Amulet_of_strength.png?15de7",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_strength",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+10",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Amulet of the damned#Full": {
    "image_url": "https://oldschool.runescape.wiki/images/e/ea/Amulet_of_the_damned_%28full%29.png?45b61",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_the_damned#Full",
    "stab_atk": "+10",
    "slash_atk": "+10",
    "crush_atk": "+10",
    "magic_atk": "+10",
    "ranged_atk": "+10",
    "stab_def": "+3",
    "slash_def": "+3",
    "crush_def": "+3",
    "magic_def": "+3",
    "ranged_def": "+3",
    "str_bonus": "+6",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+3"
  },
  "Amulet of the damned#Used": {
    "image_url": "https://oldschool.runescape.wiki/images/a/a0/Amulet_of_the_damned.png?15de7",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_the_damned#Used",
    "stab_atk": "+10",
    "slash_atk": "+10",
    "crush_atk": "+10",
    "magic_atk": "+10",
    "ranged_atk": "+10",
    "stab_def": "+3",
    "slash_def": "+3",
    "crush_def": "+3",
    "magic_def": "+3",
    "ranged_def": "+3",
    "str_bonus": "+6",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+3"
  },
  "Amulet of torture": {
    "image_url": "https://oldschool.runescape.wiki/images/4/41/Amulet_of_torture.png?ec289",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_torture",
    "stab_atk": "+15",
    "slash_atk": "+15",
    "crush_atk": "+15",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+10",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+2"
  },
  "Amulet of torture (or)": {
    "image_url": "https://oldschool.runescape.wiki/images/8/80/Amulet_of_torture_%28or%29.png?ec289",
    "wiki_url": "https://oldschool.runescape.wiki/w/Amulet_of_torture_(or)",
    "stab_atk": "+15",
    "slash_atk": "+15",
    "crush_atk": "+15",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+10",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+2"
  },
  "Ancient stole": {
    "image_url": "https://oldschool.runescape.wiki/images/4/41/Ancient_stole.png?0b6b6",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ancient_stole",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+2",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+2",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+10"
  },
  "Arceuus scarf": {
    "image_url": "https://oldschool.runescape.wiki/images/0/07/Arceuus_scarf.png?c0a17",
    "wiki_url": "https://oldschool.runescape.wiki/w/Arceuus_scarf",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Armadyl pendant": {
    "image_url": "https://oldschool.runescape.wiki/images/6/67/Armadyl_pendant.png?e56f0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Armadyl_pendant",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Armadyl stole": {
    "image_url": "https://oldschool.runescape.wiki/images/c/c5/Armadyl_stole.png?e56f0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Armadyl_stole",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+2",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+2",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+10"
  },
  "Bandos stole": {
    "image_url": "https://oldschool.runescape.wiki/images/2/28/Bandos_stole.png?22c06",
    "wiki_url": "https://oldschool.runescape.wiki/w/Bandos_stole",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+2",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+2",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+10"
  },
  "Beads of the dead": {
    "image_url": "https://oldschool.runescape.wiki/images/9/96/Beads_of_the_dead.png?15de7",
    "wiki_url": "https://oldschool.runescape.wiki/w/Beads_of_the_dead",
    "stab_atk": "+1",
    "slash_atk": "+1",
    "crush_atk": "+1",
    "magic_atk": "+1",
    "ranged_atk": "+1",
    "stab_def": "+1",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+1",
    "ranged_def": "+1",
    "str_bonus": "+1",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+1"
  },
  "Berserker necklace": {
    "image_url": "https://oldschool.runescape.wiki/images/7/75/Berserker_necklace.png?d6616",
    "wiki_url": "https://oldschool.runescape.wiki/w/Berserker_necklace",
    "stab_atk": "-10",
    "slash_atk": "-10",
    "crush_atk": "-10",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "-20",
    "slash_def": "-20",
    "crush_def": "-20",
    "magic_def": "-20",
    "ranged_def": "-20",
    "str_bonus": "+7",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+3"
  },
  "Berserker necklace (or)": {
    "image_url": "https://oldschool.runescape.wiki/images/f/ff/Berserker_necklace_%28or%29.png?356fd",
    "wiki_url": "https://oldschool.runescape.wiki/w/Berserker_necklace_(or)",
    "stab_atk": "-10",
    "slash_atk": "-10",
    "crush_atk": "-10",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "-20",
    "slash_def": "-20",
    "crush_def": "-20",
    "magic_def": "-20",
    "ranged_def": "-20",
    "str_bonus": "+7",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+3"
  },
  "Binding necklace": {
    "image_url": "https://oldschool.runescape.wiki/images/9/94/Binding_necklace.png?3be33",
    "wiki_url": "https://oldschool.runescape.wiki/w/Binding_necklace",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Bobble scarf": {
    "image_url": "https://oldschool.runescape.wiki/images/e/e9/Bobble_scarf.png?ada18",
    "wiki_url": "https://oldschool.runescape.wiki/w/Bobble_scarf",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Bonecrusher necklace": {
    "image_url": "https://oldschool.runescape.wiki/images/f/f2/Bonecrusher_necklace.png?9ae5a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Bonecrusher_necklace",
    "stab_atk": "+10",
    "slash_atk": "+10",
    "crush_atk": "+10",
    "magic_atk": "+10",
    "ranged_atk": "+10",
    "stab_def": "+2",
    "slash_def": "+2",
    "crush_def": "+2",
    "magic_def": "+2",
    "ranged_def": "+2",
    "str_bonus": "+2",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+12"
  },
  "Brass necklace": {
    "image_url": "https://oldschool.runescape.wiki/images/e/ef/Brass_necklace.png?05d25",
    "wiki_url": "https://oldschool.runescape.wiki/w/Brass_necklace",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Burning amulet#(1)": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b6/Burning_amulet.png?acbdf",
    "wiki_url": "https://oldschool.runescape.wiki/w/Burning_amulet#(1)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Burning amulet#(2)": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b6/Burning_amulet.png?acbdf",
    "wiki_url": "https://oldschool.runescape.wiki/w/Burning_amulet#(2)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Burning amulet#(3)": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b6/Burning_amulet.png?acbdf",
    "wiki_url": "https://oldschool.runescape.wiki/w/Burning_amulet#(3)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Burning amulet#(4)": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b6/Burning_amulet.png?acbdf",
    "wiki_url": "https://oldschool.runescape.wiki/w/Burning_amulet#(4)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Burning amulet#(5)": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b6/Burning_amulet.png?acbdf",
    "wiki_url": "https://oldschool.runescape.wiki/w/Burning_amulet#(5)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Camulet": {
    "image_url": "https://oldschool.runescape.wiki/images/f/f7/Camulet.png?39d34",
    "wiki_url": "https://oldschool.runescape.wiki/w/Camulet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Cat training medal": {
    "image_url": "https://oldschool.runescape.wiki/images/e/e7/Cat_training_medal.png?39d34",
    "wiki_url": "https://oldschool.runescape.wiki/w/Cat_training_medal",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Catspeak amulet": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b6/Catspeak_amulet.png?39d34",
    "wiki_url": "https://oldschool.runescape.wiki/w/Catspeak_amulet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Catspeak amulet(e)": {
    "image_url": "https://oldschool.runescape.wiki/images/1/1e/Catspeak_amulet%28e%29.png?4e200",
    "wiki_url": "https://oldschool.runescape.wiki/w/Catspeak_amulet(e)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Clean necklace": {
    "image_url": "https://oldschool.runescape.wiki/images/d/d1/Clean_necklace.png?36657",
    "wiki_url": "https://oldschool.runescape.wiki/w/Clean_necklace",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Clown bow tie#During_event": {
    "image_url": "https://oldschool.runescape.wiki/images/e/e0/Clown_bow_tie.png?09bb0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Clown_bow_tie#During_event",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Clown bow tie#Reward": {
    "image_url": "https://oldschool.runescape.wiki/images/e/e0/Clown_bow_tie.png?09bb0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Clown_bow_tie#Reward",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Crone-made amulet": {
    "image_url": "https://oldschool.runescape.wiki/images/f/f7/Crone-made_amulet.png?a4d35",
    "wiki_url": "https://oldschool.runescape.wiki/w/Crone-made_amulet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Crystal pendant": {
    "image_url": "https://oldschool.runescape.wiki/images/8/88/Crystal_pendant.png?1bbcf",
    "wiki_url": "https://oldschool.runescape.wiki/w/Crystal_pendant",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Dark bow tie": {
    "image_url": "https://oldschool.runescape.wiki/images/8/84/Dark_bow_tie.png?4806b",
    "wiki_url": "https://oldschool.runescape.wiki/w/Dark_bow_tie",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Desert amulet 1": {
    "image_url": "https://oldschool.runescape.wiki/images/6/6e/Desert_amulet_1.png?4806b",
    "wiki_url": "https://oldschool.runescape.wiki/w/Desert_amulet_1",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Desert amulet 2": {
    "image_url": "https://oldschool.runescape.wiki/images/f/fa/Desert_amulet_2.png?2c9d4",
    "wiki_url": "https://oldschool.runescape.wiki/w/Desert_amulet_2",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Desert amulet 3": {
    "image_url": "https://oldschool.runescape.wiki/images/a/af/Desert_amulet_3.png?3043c",
    "wiki_url": "https://oldschool.runescape.wiki/w/Desert_amulet_3",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Desert amulet 4": {
    "image_url": "https://oldschool.runescape.wiki/images/8/8f/Desert_amulet_4.png?3043c",
    "wiki_url": "https://oldschool.runescape.wiki/w/Desert_amulet_4",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Diamond amulet": {
    "image_url": "https://oldschool.runescape.wiki/images/4/48/Diamond_amulet.png?3043c",
    "wiki_url": "https://oldschool.runescape.wiki/w/Diamond_amulet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Diamond necklace": {
    "image_url": "https://oldschool.runescape.wiki/images/e/ea/Diamond_necklace.png?3043c",
    "wiki_url": "https://oldschool.runescape.wiki/w/Diamond_necklace",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Digsite pendant#(1)": {
    "image_url": "https://oldschool.runescape.wiki/images/7/7c/Digsite_pendant.png?3043c",
    "wiki_url": "https://oldschool.runescape.wiki/w/Digsite_pendant#(1)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Digsite pendant#(2)": {
    "image_url": "https://oldschool.runescape.wiki/images/7/7c/Digsite_pendant.png?3043c",
    "wiki_url": "https://oldschool.runescape.wiki/w/Digsite_pendant#(2)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Digsite pendant#(3)": {
    "image_url": "https://oldschool.runescape.wiki/images/7/7c/Digsite_pendant.png?3043c",
    "wiki_url": "https://oldschool.runescape.wiki/w/Digsite_pendant#(3)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Digsite pendant#(4)": {
    "image_url": "https://oldschool.runescape.wiki/images/7/7c/Digsite_pendant.png?3043c",
    "wiki_url": "https://oldschool.runescape.wiki/w/Digsite_pendant#(4)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Digsite pendant#(5)": {
    "image_url": "https://oldschool.runescape.wiki/images/7/7c/Digsite_pendant.png?3043c",
    "wiki_url": "https://oldschool.runescape.wiki/w/Digsite_pendant#(5)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Dodgy necklace": {
    "image_url": "https://oldschool.runescape.wiki/images/6/69/Dodgy_necklace.png?e2602",
    "wiki_url": "https://oldschool.runescape.wiki/w/Dodgy_necklace",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Dragon necklace": {
    "image_url": "https://oldschool.runescape.wiki/images/f/f9/Dragon_necklace.png?cc5f3",
    "wiki_url": "https://oldschool.runescape.wiki/w/Dragon_necklace",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Dragonbone necklace": {
    "image_url": "https://oldschool.runescape.wiki/images/7/7d/Dragonbone_necklace.png?8fa13",
    "wiki_url": "https://oldschool.runescape.wiki/w/Dragonbone_necklace",
    "stab_atk": "+10",
    "slash_atk": "+10",
    "crush_atk": "+10",
    "magic_atk": "+10",
    "ranged_atk": "+10",
    "stab_def": "+2",
    "slash_def": "+2",
    "crush_def": "+2",
    "magic_def": "+2",
    "ranged_def": "+2",
    "str_bonus": "+2",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+12"
  },
  "Dragonstone amulet": {
    "image_url": "https://oldschool.runescape.wiki/images/c/c2/Dragonstone_amulet.png?0b998",
    "wiki_url": "https://oldschool.runescape.wiki/w/Dragonstone_amulet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Drakan's medallion": {
    "image_url": "https://oldschool.runescape.wiki/images/a/a9/Drakan%27s_medallion.png?5eb13",
    "wiki_url": "https://oldschool.runescape.wiki/w/Drakan%27s_medallion",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Emerald amulet": {
    "image_url": "https://oldschool.runescape.wiki/images/f/fd/Emerald_amulet.png?ef54e",
    "wiki_url": "https://oldschool.runescape.wiki/w/Emerald_amulet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Emerald necklace": {
    "image_url": "https://oldschool.runescape.wiki/images/0/01/Emerald_necklace.png?1bc1e",
    "wiki_url": "https://oldschool.runescape.wiki/w/Emerald_necklace",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Games necklace#(1)": {
    "image_url": "https://oldschool.runescape.wiki/images/4/41/Games_necklace.png?7d47a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Games_necklace#(1)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Games necklace#(2)": {
    "image_url": "https://oldschool.runescape.wiki/images/4/41/Games_necklace.png?7d47a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Games_necklace#(2)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Games necklace#(3)": {
    "image_url": "https://oldschool.runescape.wiki/images/4/41/Games_necklace.png?7d47a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Games_necklace#(3)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Games necklace#(4)": {
    "image_url": "https://oldschool.runescape.wiki/images/4/41/Games_necklace.png?7d47a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Games_necklace#(4)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Games necklace#(5)": {
    "image_url": "https://oldschool.runescape.wiki/images/4/41/Games_necklace.png?7d47a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Games_necklace#(5)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Games necklace#(6)": {
    "image_url": "https://oldschool.runescape.wiki/images/4/41/Games_necklace.png?7d47a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Games_necklace#(6)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Games necklace#(7)": {
    "image_url": "https://oldschool.runescape.wiki/images/4/41/Games_necklace.png?7d47a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Games_necklace#(7)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Games necklace#(8)": {
    "image_url": "https://oldschool.runescape.wiki/images/1/19/Games_necklace%288%29.png?3b568",
    "wiki_url": "https://oldschool.runescape.wiki/w/Games_necklace#(8)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ghostspeak amulet#Enchanted": {
    "image_url": "https://oldschool.runescape.wiki/images/3/3f/Ghostspeak_amulet_%28enchanted%29.png?d2266",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ghostspeak_amulet#Enchanted",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ghostspeak amulet#Normal": {
    "image_url": "https://oldschool.runescape.wiki/images/5/5d/Ghostspeak_amulet.png?d2266",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ghostspeak_amulet#Normal",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Glarial's amulet": {
    "image_url": "https://oldschool.runescape.wiki/images/9/98/Glarial%27s_amulet.png?19135",
    "wiki_url": "https://oldschool.runescape.wiki/w/Glarial%27s_amulet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Gnome amulet": {
    "image_url": "https://oldschool.runescape.wiki/images/a/a4/Gnome_amulet.png?caa5a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Gnome_amulet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+13",
    "slash_def": "+13",
    "crush_def": "+13",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Gnome scarf": {
    "image_url": "https://oldschool.runescape.wiki/images/3/3a/Gnome_scarf.png?64612",
    "wiki_url": "https://oldschool.runescape.wiki/w/Gnome_scarf",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Gold amulet": {
    "image_url": "https://oldschool.runescape.wiki/images/d/d4/Gold_amulet.png?fc2ef",
    "wiki_url": "https://oldschool.runescape.wiki/w/Gold_amulet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Gold necklace": {
    "image_url": "https://oldschool.runescape.wiki/images/5/56/Gold_necklace.png?fc2ef",
    "wiki_url": "https://oldschool.runescape.wiki/w/Gold_necklace",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Guthix stole": {
    "image_url": "https://oldschool.runescape.wiki/images/7/74/Guthix_stole.png?98c63",
    "wiki_url": "https://oldschool.runescape.wiki/w/Guthix_stole",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+2",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+2",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+10"
  },
  "Hallowed symbol": {
    "image_url": "https://oldschool.runescape.wiki/images/7/70/Hallowed_symbol.png?20d11",
    "wiki_url": "https://oldschool.runescape.wiki/w/Hallowed_symbol",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ham logo": {
    "image_url": "https://oldschool.runescape.wiki/images/f/f3/Ham_logo.png?43cf2",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ham_logo",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Hazeel's mark": {
    "image_url": "https://oldschool.runescape.wiki/images/4/42/Hazeel%27s_mark.png?28729",
    "wiki_url": "https://oldschool.runescape.wiki/w/Hazeel%27s_mark",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Holy symbol": {
    "image_url": "https://oldschool.runescape.wiki/images/8/8b/Holy_symbol.png?e2748",
    "wiki_url": "https://oldschool.runescape.wiki/w/Holy_symbol",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+2",
    "slash_def": "+2",
    "crush_def": "+2",
    "magic_def": "+2",
    "ranged_def": "+2",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+8"
  },
  "Hosidius scarf": {
    "image_url": "https://oldschool.runescape.wiki/images/c/c8/Hosidius_scarf.png?e2748",
    "wiki_url": "https://oldschool.runescape.wiki/w/Hosidius_scarf",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Jade amulet": {
    "image_url": "https://oldschool.runescape.wiki/images/9/95/Jade_amulet.png?c27a4",
    "wiki_url": "https://oldschool.runescape.wiki/w/Jade_amulet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Jade necklace": {
    "image_url": "https://oldschool.runescape.wiki/images/4/4c/Jade_necklace.png?c27a4",
    "wiki_url": "https://oldschool.runescape.wiki/w/Jade_necklace",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Jester scarf": {
    "image_url": "https://oldschool.runescape.wiki/images/8/81/Jester_scarf.png?de0a9",
    "wiki_url": "https://oldschool.runescape.wiki/w/Jester_scarf",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Light bow tie": {
    "image_url": "https://oldschool.runescape.wiki/images/5/59/Light_bow_tie.png?8cc7e",
    "wiki_url": "https://oldschool.runescape.wiki/w/Light_bow_tie",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Lovakengj scarf": {
    "image_url": "https://oldschool.runescape.wiki/images/7/74/Lovakengj_scarf.png?8bd5a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Lovakengj_scarf",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Lunar amulet": {
    "image_url": "https://oldschool.runescape.wiki/images/6/64/Lunar_amulet.png?8bd5a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Lunar_amulet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+1",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+1",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "M'speak amulet": {
    "image_url": "https://oldschool.runescape.wiki/images/7/71/M%27speak_amulet.png?de10d",
    "wiki_url": "https://oldschool.runescape.wiki/w/M%27speak_amulet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Necklace of anguish": {
    "image_url": "https://oldschool.runescape.wiki/images/5/55/Necklace_of_anguish.png?1f378",
    "wiki_url": "https://oldschool.runescape.wiki/w/Necklace_of_anguish",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+15",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+5",
    "magic_str_bonus": "+0%",
    "prayer": "+2"
  },
  "Necklace of anguish (or)": {
    "image_url": "https://oldschool.runescape.wiki/images/0/0a/Necklace_of_anguish_%28or%29.png?7f775",
    "wiki_url": "https://oldschool.runescape.wiki/w/Necklace_of_anguish_(or)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+15",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+5",
    "magic_str_bonus": "+0%",
    "prayer": "+2"
  },
  "Necklace of faith": {
    "image_url": "https://oldschool.runescape.wiki/images/d/d2/Necklace_of_faith.png?a31da",
    "wiki_url": "https://oldschool.runescape.wiki/w/Necklace_of_faith",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Necklace of passage#(1)": {
    "image_url": "https://oldschool.runescape.wiki/images/6/62/Necklace_of_passage.png?8393a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Necklace_of_passage#(1)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Necklace of passage#(2)": {
    "image_url": "https://oldschool.runescape.wiki/images/6/62/Necklace_of_passage.png?8393a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Necklace_of_passage#(2)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Necklace of passage#(3)": {
    "image_url": "https://oldschool.runescape.wiki/images/6/62/Necklace_of_passage.png?8393a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Necklace_of_passage#(3)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Necklace of passage#(4)": {
    "image_url": "https://oldschool.runescape.wiki/images/6/62/Necklace_of_passage.png?8393a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Necklace_of_passage#(4)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Necklace of passage#(5)": {
    "image_url": "https://oldschool.runescape.wiki/images/6/62/Necklace_of_passage.png?8393a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Necklace_of_passage#(5)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Occult necklace": {
    "image_url": "https://oldschool.runescape.wiki/images/f/f7/Occult_necklace.png?7df05",
    "wiki_url": "https://oldschool.runescape.wiki/w/Occult_necklace",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+12",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+10%",
    "prayer": "+2"
  },
  "Occult necklace (Last Man Standing)": {
    "image_url": "https://oldschool.runescape.wiki/images/f/f4/Occult_necklace_%28Last_Man_Standing%29.png?7df05",
    "wiki_url": "https://oldschool.runescape.wiki/w/Occult_necklace_(Last_Man_Standing)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+12",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+10%",
    "prayer": "+2"
  },
  "Occult necklace (or)": {
    "image_url": "https://oldschool.runescape.wiki/images/3/32/Occult_necklace_%28or%29.png?7df05",
    "wiki_url": "https://oldschool.runescape.wiki/w/Occult_necklace_(or)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+12",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+10%",
    "prayer": "+2"
  },
  "Onyx amulet": {
    "image_url": "https://oldschool.runescape.wiki/images/4/4d/Onyx_amulet.png?56826",
    "wiki_url": "https://oldschool.runescape.wiki/w/Onyx_amulet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Onyx necklace": {
    "image_url": "https://oldschool.runescape.wiki/images/5/51/Onyx_necklace.png?fe846",
    "wiki_url": "https://oldschool.runescape.wiki/w/Onyx_necklace",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Opal amulet": {
    "image_url": "https://oldschool.runescape.wiki/images/a/a2/Opal_amulet.png?8bdb9",
    "wiki_url": "https://oldschool.runescape.wiki/w/Opal_amulet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Opal necklace": {
    "image_url": "https://oldschool.runescape.wiki/images/5/51/Opal_necklace.png?8bdb9",
    "wiki_url": "https://oldschool.runescape.wiki/w/Opal_necklace",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Pendant of lucien": {
    "image_url": "https://oldschool.runescape.wiki/images/2/2e/Pendant_of_lucien.png?174e0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Pendant_of_lucien",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Phoenix necklace": {
    "image_url": "https://oldschool.runescape.wiki/images/f/ff/Phoenix_necklace.png?3a750",
    "wiki_url": "https://oldschool.runescape.wiki/w/Phoenix_necklace",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Piscarilius scarf": {
    "image_url": "https://oldschool.runescape.wiki/images/4/4c/Piscarilius_scarf.png?bbceb",
    "wiki_url": "https://oldschool.runescape.wiki/w/Piscarilius_scarf",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Pre-nature amulet": {
    "image_url": "https://oldschool.runescape.wiki/images/1/16/Pre-nature_amulet.png?e2ec4",
    "wiki_url": "https://oldschool.runescape.wiki/w/Pre-nature_amulet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Rainbow scarf": {
    "image_url": "https://oldschool.runescape.wiki/images/d/d9/Rainbow_scarf.png?095ed",
    "wiki_url": "https://oldschool.runescape.wiki/w/Rainbow_scarf",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ruby amulet": {
    "image_url": "https://oldschool.runescape.wiki/images/3/3a/Ruby_amulet.png?625fb",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ruby_amulet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ruby necklace": {
    "image_url": "https://oldschool.runescape.wiki/images/6/64/Ruby_necklace.png?625fb",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ruby_necklace",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Salve amulet": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b9/Salve_amulet.png?a8fa6",
    "wiki_url": "https://oldschool.runescape.wiki/w/Salve_amulet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+3",
    "slash_def": "+3",
    "crush_def": "+3",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+3"
  },
  "Salve amulet (e)": {
    "image_url": "https://oldschool.runescape.wiki/images/b/bc/Salve_amulet_%28e%29.png?a8fa6",
    "wiki_url": "https://oldschool.runescape.wiki/w/Salve_amulet_(e)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+3",
    "slash_def": "+3",
    "crush_def": "+3",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+3"
  },
  "Salve amulet(ei)#Nightmare_Zone": {
    "image_url": "https://oldschool.runescape.wiki/images/d/d2/Salve_amulet%28ei%29.png?a8fa6",
    "wiki_url": "https://oldschool.runescape.wiki/w/Salve_amulet(ei)#Nightmare_Zone",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+3",
    "slash_def": "+3",
    "crush_def": "+3",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+3"
  },
  "Salve amulet(ei)#Soul_Wars": {
    "image_url": "https://oldschool.runescape.wiki/images/d/d2/Salve_amulet%28ei%29.png?a8fa6",
    "wiki_url": "https://oldschool.runescape.wiki/w/Salve_amulet(ei)#Soul_Wars",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+3",
    "slash_def": "+3",
    "crush_def": "+3",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+3"
  },
  "Salve amulet(i)#Nightmare_Zone": {
    "image_url": "https://oldschool.runescape.wiki/images/1/14/Salve_amulet%28i%29.png?a8fa6",
    "wiki_url": "https://oldschool.runescape.wiki/w/Salve_amulet(i)#Nightmare_Zone",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+3",
    "slash_def": "+3",
    "crush_def": "+3",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+3"
  },
  "Salve amulet(i)#Soul_Wars": {
    "image_url": "https://oldschool.runescape.wiki/images/1/14/Salve_amulet%28i%29.png?a8fa6",
    "wiki_url": "https://oldschool.runescape.wiki/w/Salve_amulet(i)#Soul_Wars",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+3",
    "slash_def": "+3",
    "crush_def": "+3",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+3"
  },
  "Sapphire amulet": {
    "image_url": "https://oldschool.runescape.wiki/images/3/3d/Sapphire_amulet.png?3f71e",
    "wiki_url": "https://oldschool.runescape.wiki/w/Sapphire_amulet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Sapphire necklace": {
    "image_url": "https://oldschool.runescape.wiki/images/e/ed/Sapphire_necklace.png?11815",
    "wiki_url": "https://oldschool.runescape.wiki/w/Sapphire_necklace",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Saradomin stole": {
    "image_url": "https://oldschool.runescape.wiki/images/6/6e/Saradomin_stole.png?462fd",
    "wiki_url": "https://oldschool.runescape.wiki/w/Saradomin_stole",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+2",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+2",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+10"
  },
  "Seal of passage": {
    "image_url": "https://oldschool.runescape.wiki/images/e/ea/Seal_of_passage.png?462fd",
    "wiki_url": "https://oldschool.runescape.wiki/w/Seal_of_passage",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Shayzien scarf": {
    "image_url": "https://oldschool.runescape.wiki/images/8/8b/Shayzien_scarf.png?4b960",
    "wiki_url": "https://oldschool.runescape.wiki/w/Shayzien_scarf",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Silver necklace#Dusted": {
    "image_url": "https://oldschool.runescape.wiki/images/a/a2/Silver_necklace.png?3caa3",
    "wiki_url": "https://oldschool.runescape.wiki/w/Silver_necklace#Dusted",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Silver necklace#Normal": {
    "image_url": "https://oldschool.runescape.wiki/images/a/a2/Silver_necklace.png?3caa3",
    "wiki_url": "https://oldschool.runescape.wiki/w/Silver_necklace#Normal",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Skills necklace#(1)": {
    "image_url": "https://oldschool.runescape.wiki/images/0/06/Skills_necklace.png?f1c54",
    "wiki_url": "https://oldschool.runescape.wiki/w/Skills_necklace#(1)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Skills necklace#(2)": {
    "image_url": "https://oldschool.runescape.wiki/images/0/06/Skills_necklace.png?f1c54",
    "wiki_url": "https://oldschool.runescape.wiki/w/Skills_necklace#(2)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Skills necklace#(3)": {
    "image_url": "https://oldschool.runescape.wiki/images/0/06/Skills_necklace.png?f1c54",
    "wiki_url": "https://oldschool.runescape.wiki/w/Skills_necklace#(3)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Skills necklace#(4)": {
    "image_url": "https://oldschool.runescape.wiki/images/0/06/Skills_necklace.png?f1c54",
    "wiki_url": "https://oldschool.runescape.wiki/w/Skills_necklace#(4)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Skills necklace#(5)": {
    "image_url": "https://oldschool.runescape.wiki/images/0/06/Skills_necklace.png?f1c54",
    "wiki_url": "https://oldschool.runescape.wiki/w/Skills_necklace#(5)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Skills necklace#(6)": {
    "image_url": "https://oldschool.runescape.wiki/images/0/06/Skills_necklace.png?f1c54",
    "wiki_url": "https://oldschool.runescape.wiki/w/Skills_necklace#(6)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Skills necklace#Uncharged": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b1/Skills_necklace_%28uncharged%29.png?1d1f2",
    "wiki_url": "https://oldschool.runescape.wiki/w/Skills_necklace#Uncharged",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Strength amulet (t)": {
    "image_url": "https://oldschool.runescape.wiki/images/1/11/Strength_amulet_%28t%29.png?e42b7",
    "wiki_url": "https://oldschool.runescape.wiki/w/Strength_amulet_(t)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+10",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Strung rabbit foot": {
    "image_url": "https://oldschool.runescape.wiki/images/4/45/Strung_rabbit_foot.png?210aa",
    "wiki_url": "https://oldschool.runescape.wiki/w/Strung_rabbit_foot",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Topaz amulet": {
    "image_url": "https://oldschool.runescape.wiki/images/9/94/Topaz_amulet.png?04f28",
    "wiki_url": "https://oldschool.runescape.wiki/w/Topaz_amulet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Topaz necklace": {
    "image_url": "https://oldschool.runescape.wiki/images/4/4e/Topaz_necklace.png?04f28",
    "wiki_url": "https://oldschool.runescape.wiki/w/Topaz_necklace",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Tri-jester scarf": {
    "image_url": "https://oldschool.runescape.wiki/images/d/d2/Tri-jester_scarf.png?5c5a6",
    "wiki_url": "https://oldschool.runescape.wiki/w/Tri-jester_scarf",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Unblessed symbol": {
    "image_url": "https://oldschool.runescape.wiki/images/d/db/Unblessed_symbol.png?fc550",
    "wiki_url": "https://oldschool.runescape.wiki/w/Unblessed_symbol",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Unholy symbol": {
    "image_url": "https://oldschool.runescape.wiki/images/0/00/Unholy_symbol.png?4a467",
    "wiki_url": "https://oldschool.runescape.wiki/w/Unholy_symbol",
    "stab_atk": "+2",
    "slash_atk": "+2",
    "crush_atk": "+2",
    "magic_atk": "+2",
    "ranged_atk": "+2",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+8"
  },
  "Unpowered symbol": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b9/Unpowered_symbol.png?e3acf",
    "wiki_url": "https://oldschool.runescape.wiki/w/Unpowered_symbol",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Void seal#(1)": {
    "image_url": "https://oldschool.runescape.wiki/images/8/8e/Void_seal.png?b7686",
    "wiki_url": "https://oldschool.runescape.wiki/w/Void_seal#(1)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+1",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+1",
    "ranged_def": "+1",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Void seal#(2)": {
    "image_url": "https://oldschool.runescape.wiki/images/8/8e/Void_seal.png?b7686",
    "wiki_url": "https://oldschool.runescape.wiki/w/Void_seal#(2)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+1",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+1",
    "ranged_def": "+1",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Void seal#(3)": {
    "image_url": "https://oldschool.runescape.wiki/images/8/8e/Void_seal.png?b7686",
    "wiki_url": "https://oldschool.runescape.wiki/w/Void_seal#(3)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+1",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+1",
    "ranged_def": "+1",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Void seal#(4)": {
    "image_url": "https://oldschool.runescape.wiki/images/8/8e/Void_seal.png?b7686",
    "wiki_url": "https://oldschool.runescape.wiki/w/Void_seal#(4)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+1",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+1",
    "ranged_def": "+1",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Void seal#(5)": {
    "image_url": "https://oldschool.runescape.wiki/images/8/8e/Void_seal.png?b7686",
    "wiki_url": "https://oldschool.runescape.wiki/w/Void_seal#(5)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+1",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+1",
    "ranged_def": "+1",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Void seal#(6)": {
    "image_url": "https://oldschool.runescape.wiki/images/8/8e/Void_seal.png?b7686",
    "wiki_url": "https://oldschool.runescape.wiki/w/Void_seal#(6)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+1",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+1",
    "ranged_def": "+1",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Void seal#(7)": {
    "image_url": "https://oldschool.runescape.wiki/images/8/8e/Void_seal.png?b7686",
    "wiki_url": "https://oldschool.runescape.wiki/w/Void_seal#(7)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+1",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+1",
    "ranged_def": "+1",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Void seal#(8)": {
    "image_url": "https://oldschool.runescape.wiki/images/8/8e/Void_seal.png?b7686",
    "wiki_url": "https://oldschool.runescape.wiki/w/Void_seal#(8)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+1",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+1",
    "ranged_def": "+1",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Witchwood icon": {
    "image_url": "https://oldschool.runescape.wiki/images/e/ef/Witchwood_icon.png?d2390",
    "wiki_url": "https://oldschool.runescape.wiki/w/Witchwood_icon",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+1",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+1"
  },
  "Woolly scarf": {
    "image_url": "https://oldschool.runescape.wiki/images/8/87/Woolly_scarf.png?819f7",
    "wiki_url": "https://oldschool.runescape.wiki/w/Woolly_scarf",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Xeric's talisman#Charged": {
    "image_url": "https://oldschool.runescape.wiki/images/3/3c/Xeric%27s_talisman.png?046c7",
    "wiki_url": "https://oldschool.runescape.wiki/w/Xeric%27s_talisman#Charged",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+3",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+1",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Xeric's talisman#Inert": {
    "image_url": "https://oldschool.runescape.wiki/images/e/e4/Xeric%27s_talisman_%28inert%29.png?046c7",
    "wiki_url": "https://oldschool.runescape.wiki/w/Xeric%27s_talisman#Inert",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+2",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Yin yang amulet": {
    "image_url": "https://oldschool.runescape.wiki/images/1/17/Yin_yang_amulet.png?faa5d",
    "wiki_url": "https://oldschool.runescape.wiki/w/Yin_yang_amulet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Zamorak stole": {
    "image_url": "https://oldschool.runescape.wiki/images/0/0c/Zamorak_stole.png?8abb8",
    "wiki_url": "https://oldschool.runescape.wiki/w/Zamorak_stole",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+2",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+2",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+10"
  },
  "Zenyte amulet": {
    "image_url": "https://oldschool.runescape.wiki/images/1/10/Zenyte_amulet.png?53a8d",
    "wiki_url": "https://oldschool.runescape.wiki/w/Zenyte_amulet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Zenyte necklace": {
    "image_url": "https://oldschool.runescape.wiki/images/0/0f/Zenyte_necklace.png?37c64",
    "wiki_url": "https://oldschool.runescape.wiki/w/Zenyte_necklace",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "'perfect' necklace": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b1/%27perfect%27_necklace.png?3dda6",
    "wiki_url": "https://oldschool.runescape.wiki/w/%27perfect%27_necklace",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  }
}