window.equipment.ring = {
  "Archers ring": {
    "image_url": "https://oldschool.runescape.wiki/images/d/d6/Archers_ring.png?c0a17",
    "wiki_url": "https://oldschool.runescape.wiki/w/Archers_ring",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+4",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+4",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Archers ring (i)#Nightmare_Zone": {
    "image_url": "https://oldschool.runescape.wiki/images/b/bd/Archers_ring_%28i%29.png?1f712",
    "wiki_url": "https://oldschool.runescape.wiki/w/Archers_ring_(i)#Nightmare_Zone",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+8",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+8",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Archers ring (i)#Soul_Wars": {
    "image_url": "https://oldschool.runescape.wiki/images/b/bd/Archers_ring_%28i%29.png?1f712",
    "wiki_url": "https://oldschool.runescape.wiki/w/Archers_ring_(i)#Soul_Wars",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+8",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+8",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Beacon ring": {
    "image_url": "https://oldschool.runescape.wiki/images/e/e0/Beacon_ring.png?3be33",
    "wiki_url": "https://oldschool.runescape.wiki/w/Beacon_ring",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+2",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+1",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Berserker ring": {
    "image_url": "https://oldschool.runescape.wiki/images/c/c5/Berserker_ring.png?3be33",
    "wiki_url": "https://oldschool.runescape.wiki/w/Berserker_ring",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+4",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+4",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Berserker ring (Last Man Standing)": {
    "image_url": "https://oldschool.runescape.wiki/images/0/08/Berserker_ring_%28Last_Man_Standing%29.png?3be33",
    "wiki_url": "https://oldschool.runescape.wiki/w/Berserker_ring_(Last_Man_Standing)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+4",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+4",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Berserker ring (i)#Nightmare_Zone": {
    "image_url": "https://oldschool.runescape.wiki/images/7/72/Berserker_ring_%28i%29.png?356fd",
    "wiki_url": "https://oldschool.runescape.wiki/w/Berserker_ring_(i)#Nightmare_Zone",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+8",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+8",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Berserker ring (i)#Soul_Wars": {
    "image_url": "https://oldschool.runescape.wiki/images/7/72/Berserker_ring_%28i%29.png?356fd",
    "wiki_url": "https://oldschool.runescape.wiki/w/Berserker_ring_(i)#Soul_Wars",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+8",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+8",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Brimstone ring": {
    "image_url": "https://oldschool.runescape.wiki/images/9/91/Brimstone_ring.png?3d026",
    "wiki_url": "https://oldschool.runescape.wiki/w/Brimstone_ring",
    "stab_atk": "+4",
    "slash_atk": "+4",
    "crush_atk": "+4",
    "magic_atk": "+6",
    "ranged_atk": "+4",
    "stab_def": "+4",
    "slash_def": "+4",
    "crush_def": "+4",
    "magic_def": "+6",
    "ranged_def": "+4",
    "str_bonus": "+4",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Celestial ring#Charged": {
    "image_url": "https://oldschool.runescape.wiki/images/c/c4/Celestial_ring.png?273ca",
    "wiki_url": "https://oldschool.runescape.wiki/w/Celestial_ring#Charged",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Celestial ring#Uncharged": {
    "image_url": "https://oldschool.runescape.wiki/images/7/7f/Celestial_ring_%28uncharged%29.png?273ca",
    "wiki_url": "https://oldschool.runescape.wiki/w/Celestial_ring#Uncharged",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Celestial signet#Charged": {
    "image_url": "https://oldschool.runescape.wiki/images/1/1e/Celestial_signet.png?273ca",
    "wiki_url": "https://oldschool.runescape.wiki/w/Celestial_signet#Charged",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Celestial signet#Uncharged": {
    "image_url": "https://oldschool.runescape.wiki/images/5/59/Celestial_signet_%28uncharged%29.png?39d34",
    "wiki_url": "https://oldschool.runescape.wiki/w/Celestial_signet#Uncharged",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Diamond ring": {
    "image_url": "https://oldschool.runescape.wiki/images/5/5d/Diamond_ring.png?2c9d4",
    "wiki_url": "https://oldschool.runescape.wiki/w/Diamond_ring",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Dragonstone ring": {
    "image_url": "https://oldschool.runescape.wiki/images/d/dd/Dragonstone_ring.png?5eb13",
    "wiki_url": "https://oldschool.runescape.wiki/w/Dragonstone_ring",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Easter ring": {
    "image_url": "https://oldschool.runescape.wiki/images/0/0a/Easter_ring.png?0a875",
    "wiki_url": "https://oldschool.runescape.wiki/w/Easter_ring",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Efaritay's aid": {
    "image_url": "https://oldschool.runescape.wiki/images/a/a2/Efaritay%27s_aid.png?7a7c0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Efaritay%27s_aid",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Elven signet": {
    "image_url": "https://oldschool.runescape.wiki/images/9/91/Elven_signet.png?1bc1e",
    "wiki_url": "https://oldschool.runescape.wiki/w/Elven_signet",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Emerald ring": {
    "image_url": "https://oldschool.runescape.wiki/images/5/5d/Emerald_ring.png?7a7c0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Emerald_ring",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Explorer's ring 1": {
    "image_url": "https://oldschool.runescape.wiki/images/8/84/Explorer%27s_ring_1.png?b8cf0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Explorer%27s_ring_1",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+1"
  },
  "Explorer's ring 2": {
    "image_url": "https://oldschool.runescape.wiki/images/1/14/Explorer%27s_ring_2.png?97fe8",
    "wiki_url": "https://oldschool.runescape.wiki/w/Explorer%27s_ring_2",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+1"
  },
  "Explorer's ring 3": {
    "image_url": "https://oldschool.runescape.wiki/images/4/4a/Explorer%27s_ring_3.png?b8cf0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Explorer%27s_ring_3",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+1"
  },
  "Explorer's ring 4": {
    "image_url": "https://oldschool.runescape.wiki/images/2/20/Explorer%27s_ring_4.png?b8cf0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Explorer%27s_ring_4",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+1"
  },
  "Gold ring": {
    "image_url": "https://oldschool.runescape.wiki/images/a/ae/Gold_ring.png?fc2ef",
    "wiki_url": "https://oldschool.runescape.wiki/w/Gold_ring",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Granite ring": {
    "image_url": "https://oldschool.runescape.wiki/images/c/c0/Granite_ring.png?4e070",
    "wiki_url": "https://oldschool.runescape.wiki/w/Granite_ring",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+2",
    "slash_def": "+2",
    "crush_def": "+2",
    "magic_def": "-2",
    "ranged_def": "+8",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Granite ring (i)#Nightmare_Zone": {
    "image_url": "https://oldschool.runescape.wiki/images/6/65/Granite_ring_%28i%29.png?99c22",
    "wiki_url": "https://oldschool.runescape.wiki/w/Granite_ring_(i)#Nightmare_Zone",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+4",
    "slash_def": "+4",
    "crush_def": "+4",
    "magic_def": "-4",
    "ranged_def": "+16",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Granite ring (i)#Soul_Wars": {
    "image_url": "https://oldschool.runescape.wiki/images/6/65/Granite_ring_%28i%29.png?99c22",
    "wiki_url": "https://oldschool.runescape.wiki/w/Granite_ring_(i)#Soul_Wars",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+4",
    "slash_def": "+4",
    "crush_def": "+4",
    "magic_def": "-4",
    "ranged_def": "+16",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Hallowed ring": {
    "image_url": "https://oldschool.runescape.wiki/images/7/78/Hallowed_ring.png?20d11",
    "wiki_url": "https://oldschool.runescape.wiki/w/Hallowed_ring",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Jade ring": {
    "image_url": "https://oldschool.runescape.wiki/images/3/36/Jade_ring.png?c27a4",
    "wiki_url": "https://oldschool.runescape.wiki/w/Jade_ring",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Lunar ring": {
    "image_url": "https://oldschool.runescape.wiki/images/a/ac/Lunar_ring.png?6dc61",
    "wiki_url": "https://oldschool.runescape.wiki/w/Lunar_ring",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+2",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+2",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Onyx ring": {
    "image_url": "https://oldschool.runescape.wiki/images/a/a4/Onyx_ring.png?8bdb9",
    "wiki_url": "https://oldschool.runescape.wiki/w/Onyx_ring",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Opal ring": {
    "image_url": "https://oldschool.runescape.wiki/images/1/15/Opal_ring.png?8bdb9",
    "wiki_url": "https://oldschool.runescape.wiki/w/Opal_ring",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of 3rd age": {
    "image_url": "https://oldschool.runescape.wiki/images/c/c0/Ring_of_3rd_age.png?4e1b1",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_3rd_age",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of charos#Activated": {
    "image_url": "https://oldschool.runescape.wiki/images/c/cd/Ring_of_charos_%28a%29.png?dd602",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_charos#Activated",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of charos#Normal": {
    "image_url": "https://oldschool.runescape.wiki/images/2/28/Ring_of_charos.png?ed4b0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_charos#Normal",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of coins": {
    "image_url": "https://oldschool.runescape.wiki/images/1/11/Ring_of_coins.png?4e1b1",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_coins",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of dueling#(1)": {
    "image_url": "https://oldschool.runescape.wiki/images/b/bd/Ring_of_dueling.png?4f1c0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_dueling#(1)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of dueling#(2)": {
    "image_url": "https://oldschool.runescape.wiki/images/b/bd/Ring_of_dueling.png?4f1c0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_dueling#(2)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of dueling#(3)": {
    "image_url": "https://oldschool.runescape.wiki/images/b/bd/Ring_of_dueling.png?4f1c0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_dueling#(3)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of dueling#(4)": {
    "image_url": "https://oldschool.runescape.wiki/images/b/bd/Ring_of_dueling.png?4f1c0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_dueling#(4)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of dueling#(5)": {
    "image_url": "https://oldschool.runescape.wiki/images/b/bd/Ring_of_dueling.png?4f1c0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_dueling#(5)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of dueling#(6)": {
    "image_url": "https://oldschool.runescape.wiki/images/b/bd/Ring_of_dueling.png?4f1c0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_dueling#(6)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of dueling#(7)": {
    "image_url": "https://oldschool.runescape.wiki/images/b/bd/Ring_of_dueling.png?4f1c0",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_dueling#(7)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of dueling#(8)": {
    "image_url": "https://oldschool.runescape.wiki/images/6/6f/Ring_of_dueling%288%29.png?3f71e",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_dueling#(8)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of endurance#Charged": {
    "image_url": "https://oldschool.runescape.wiki/images/8/81/Ring_of_endurance.png?4e1b1",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_endurance#Charged",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of endurance#Uncharged": {
    "image_url": "https://oldschool.runescape.wiki/images/d/de/Ring_of_endurance_%28uncharged%29.png?4e1b1",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_endurance#Uncharged",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of forging": {
    "image_url": "https://oldschool.runescape.wiki/images/2/27/Ring_of_forging.png?4e1b1",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_forging",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of life": {
    "image_url": "https://oldschool.runescape.wiki/images/e/e2/Ring_of_life.png?4e1b1",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_life",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of nature": {
    "image_url": "https://oldschool.runescape.wiki/images/9/9a/Ring_of_nature.png?4e1b1",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_nature",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of pursuit": {
    "image_url": "https://oldschool.runescape.wiki/images/d/de/Ring_of_pursuit.png?c76a5",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_pursuit",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of recoil": {
    "image_url": "https://oldschool.runescape.wiki/images/9/9b/Ring_of_recoil.png?4e1b1",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_recoil",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of returning#(1)": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b1/Ring_of_returning.png?4e1b1",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_returning#(1)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of returning#(2)": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b1/Ring_of_returning.png?4e1b1",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_returning#(2)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of returning#(3)": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b1/Ring_of_returning.png?4e1b1",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_returning#(3)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of returning#(4)": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b1/Ring_of_returning.png?4e1b1",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_returning#(4)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of returning#(5)": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b1/Ring_of_returning.png?4e1b1",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_returning#(5)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of stone": {
    "image_url": "https://oldschool.runescape.wiki/images/a/a1/Ring_of_stone.png?c76a5",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_stone",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of suffering (i)#Recoil": {
    "image_url": "https://oldschool.runescape.wiki/images/b/be/Ring_of_suffering_%28i%29.png?4e1b1",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_suffering_(i)#Recoil",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+20",
    "slash_def": "+20",
    "crush_def": "+20",
    "magic_def": "+20",
    "ranged_def": "+20",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+4"
  },
  "Ring of suffering (i)#Uncharged": {
    "image_url": "https://oldschool.runescape.wiki/images/b/be/Ring_of_suffering_%28i%29.png?4e1b1",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_suffering_(i)#Uncharged",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+20",
    "slash_def": "+20",
    "crush_def": "+20",
    "magic_def": "+20",
    "ranged_def": "+20",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+4"
  },
  "Ring of suffering#Recoil": {
    "image_url": "https://oldschool.runescape.wiki/images/3/31/Ring_of_suffering.png?dd602",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_suffering#Recoil",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+10",
    "slash_def": "+10",
    "crush_def": "+10",
    "magic_def": "+10",
    "ranged_def": "+10",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+2"
  },
  "Ring of suffering#Uncharged": {
    "image_url": "https://oldschool.runescape.wiki/images/3/31/Ring_of_suffering.png?dd602",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_suffering#Uncharged",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+10",
    "slash_def": "+10",
    "crush_def": "+10",
    "magic_def": "+10",
    "ranged_def": "+10",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+2"
  },
  "Ring of the gods": {
    "image_url": "https://oldschool.runescape.wiki/images/f/f6/Ring_of_the_gods.png?4e1b1",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_the_gods",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+1",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+1",
    "ranged_def": "+1",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+4"
  },
  "Ring of the gods (i)#Nightmare_Zone": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b3/Ring_of_the_gods_%28i%29.png?c76a5",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_the_gods_(i)#Nightmare_Zone",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+1",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+1",
    "ranged_def": "+1",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+8"
  },
  "Ring of the gods (i)#Soul_Wars": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b3/Ring_of_the_gods_%28i%29.png?c76a5",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_the_gods_(i)#Soul_Wars",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+1",
    "slash_def": "+1",
    "crush_def": "+1",
    "magic_def": "+1",
    "ranged_def": "+1",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+8"
  },
  "Ring of visibility": {
    "image_url": "https://oldschool.runescape.wiki/images/7/7e/Ring_of_visibility.png?4e1b1",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_visibility",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of wealth (i)#(i1)": {
    "image_url": "https://oldschool.runescape.wiki/images/1/1c/Ring_of_wealth_%28i%29.png?4e1b1",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_wealth_(i)#(i1)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of wealth (i)#(i2)": {
    "image_url": "https://oldschool.runescape.wiki/images/1/1c/Ring_of_wealth_%28i%29.png?4e1b1",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_wealth_(i)#(i2)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of wealth (i)#(i3)": {
    "image_url": "https://oldschool.runescape.wiki/images/1/1c/Ring_of_wealth_%28i%29.png?4e1b1",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_wealth_(i)#(i3)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of wealth (i)#(i4)": {
    "image_url": "https://oldschool.runescape.wiki/images/1/1c/Ring_of_wealth_%28i%29.png?4e1b1",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_wealth_(i)#(i4)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of wealth (i)#(i5)": {
    "image_url": "https://oldschool.runescape.wiki/images/1/1c/Ring_of_wealth_%28i%29.png?4e1b1",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_wealth_(i)#(i5)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of wealth (i)#Uncharged": {
    "image_url": "https://oldschool.runescape.wiki/images/7/71/Ring_of_wealth_%28i%29_%28uncharged%29.png?e5f4c",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_wealth_(i)#Uncharged",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of wealth#(1)": {
    "image_url": "https://oldschool.runescape.wiki/images/c/c7/Ring_of_wealth.png?dd602",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_wealth#(1)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of wealth#(2)": {
    "image_url": "https://oldschool.runescape.wiki/images/c/c7/Ring_of_wealth.png?dd602",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_wealth#(2)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of wealth#(3)": {
    "image_url": "https://oldschool.runescape.wiki/images/c/c7/Ring_of_wealth.png?dd602",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_wealth#(3)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of wealth#(4)": {
    "image_url": "https://oldschool.runescape.wiki/images/c/c7/Ring_of_wealth.png?dd602",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_wealth#(4)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of wealth#(5)": {
    "image_url": "https://oldschool.runescape.wiki/images/c/c7/Ring_of_wealth.png?dd602",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_wealth#(5)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ring of wealth#Uncharged": {
    "image_url": "https://oldschool.runescape.wiki/images/1/19/Ring_of_wealth_%28uncharged%29.png?dd602",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ring_of_wealth#Uncharged",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Ruby ring": {
    "image_url": "https://oldschool.runescape.wiki/images/2/24/Ruby_ring.png?625fb",
    "wiki_url": "https://oldschool.runescape.wiki/w/Ruby_ring",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Sapphire ring": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b6/Sapphire_ring.png?0ee99",
    "wiki_url": "https://oldschool.runescape.wiki/w/Sapphire_ring",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Seers ring": {
    "image_url": "https://oldschool.runescape.wiki/images/9/90/Seers_ring.png?4b960",
    "wiki_url": "https://oldschool.runescape.wiki/w/Seers_ring",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+6",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+6",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Seers ring (i) (Last Man Standing)": {
    "image_url": "https://oldschool.runescape.wiki/images/0/0c/Seers_ring_%28i%29_%28Last_Man_Standing%29.png?f410d",
    "wiki_url": "https://oldschool.runescape.wiki/w/Seers_ring_(i)_(Last_Man_Standing)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+12",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+12",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Seers ring (i)#Nightmare_Zone": {
    "image_url": "https://oldschool.runescape.wiki/images/0/06/Seers_ring_%28i%29.png?f410d",
    "wiki_url": "https://oldschool.runescape.wiki/w/Seers_ring_(i)#Nightmare_Zone",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+12",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+12",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Seers ring (i)#Soul_Wars": {
    "image_url": "https://oldschool.runescape.wiki/images/0/06/Seers_ring_%28i%29.png?f410d",
    "wiki_url": "https://oldschool.runescape.wiki/w/Seers_ring_(i)#Soul_Wars",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+12",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+12",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Slayer ring (eternal)": {
    "image_url": "https://oldschool.runescape.wiki/images/a/ae/Slayer_ring_%28eternal%29.png?0df0a",
    "wiki_url": "https://oldschool.runescape.wiki/w/Slayer_ring_(eternal)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Slayer ring#(1)": {
    "image_url": "https://oldschool.runescape.wiki/images/9/90/Slayer_ring.png?1d1f2",
    "wiki_url": "https://oldschool.runescape.wiki/w/Slayer_ring#(1)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Slayer ring#(2)": {
    "image_url": "https://oldschool.runescape.wiki/images/9/90/Slayer_ring.png?1d1f2",
    "wiki_url": "https://oldschool.runescape.wiki/w/Slayer_ring#(2)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Slayer ring#(3)": {
    "image_url": "https://oldschool.runescape.wiki/images/9/90/Slayer_ring.png?1d1f2",
    "wiki_url": "https://oldschool.runescape.wiki/w/Slayer_ring#(3)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Slayer ring#(4)": {
    "image_url": "https://oldschool.runescape.wiki/images/9/90/Slayer_ring.png?1d1f2",
    "wiki_url": "https://oldschool.runescape.wiki/w/Slayer_ring#(4)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Slayer ring#(5)": {
    "image_url": "https://oldschool.runescape.wiki/images/9/90/Slayer_ring.png?1d1f2",
    "wiki_url": "https://oldschool.runescape.wiki/w/Slayer_ring#(5)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Slayer ring#(6)": {
    "image_url": "https://oldschool.runescape.wiki/images/9/90/Slayer_ring.png?1d1f2",
    "wiki_url": "https://oldschool.runescape.wiki/w/Slayer_ring#(6)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Slayer ring#(7)": {
    "image_url": "https://oldschool.runescape.wiki/images/9/90/Slayer_ring.png?1d1f2",
    "wiki_url": "https://oldschool.runescape.wiki/w/Slayer_ring#(7)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Slayer ring#(8)": {
    "image_url": "https://oldschool.runescape.wiki/images/9/90/Slayer_ring.png?1d1f2",
    "wiki_url": "https://oldschool.runescape.wiki/w/Slayer_ring#(8)",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Topaz ring": {
    "image_url": "https://oldschool.runescape.wiki/images/1/10/Topaz_ring.png?c9227",
    "wiki_url": "https://oldschool.runescape.wiki/w/Topaz_ring",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Treasonous ring": {
    "image_url": "https://oldschool.runescape.wiki/images/b/ba/Treasonous_ring.png?79f0d",
    "wiki_url": "https://oldschool.runescape.wiki/w/Treasonous_ring",
    "stab_atk": "+4",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+4",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Treasonous ring (i)#Nightmare_Zone": {
    "image_url": "https://oldschool.runescape.wiki/images/2/2a/Treasonous_ring_%28i%29.png?849c7",
    "wiki_url": "https://oldschool.runescape.wiki/w/Treasonous_ring_(i)#Nightmare_Zone",
    "stab_atk": "+8",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+8",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Treasonous ring (i)#Soul_Wars": {
    "image_url": "https://oldschool.runescape.wiki/images/2/2a/Treasonous_ring_%28i%29.png?849c7",
    "wiki_url": "https://oldschool.runescape.wiki/w/Treasonous_ring_(i)#Soul_Wars",
    "stab_atk": "+8",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+8",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Tyrannical ring": {
    "image_url": "https://oldschool.runescape.wiki/images/6/6f/Tyrannical_ring.png?fc550",
    "wiki_url": "https://oldschool.runescape.wiki/w/Tyrannical_ring",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+4",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+4",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Tyrannical ring (i)#Nightmare_Zone": {
    "image_url": "https://oldschool.runescape.wiki/images/c/c2/Tyrannical_ring_%28i%29.png?08f42",
    "wiki_url": "https://oldschool.runescape.wiki/w/Tyrannical_ring_(i)#Nightmare_Zone",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+8",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+8",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Tyrannical ring (i)#Soul_Wars": {
    "image_url": "https://oldschool.runescape.wiki/images/c/c2/Tyrannical_ring_%28i%29.png?08f42",
    "wiki_url": "https://oldschool.runescape.wiki/w/Tyrannical_ring_(i)#Soul_Wars",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+8",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+8",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Warrior ring": {
    "image_url": "https://oldschool.runescape.wiki/images/7/7f/Warrior_ring.png?75a26",
    "wiki_url": "https://oldschool.runescape.wiki/w/Warrior_ring",
    "stab_atk": "+0",
    "slash_atk": "+4",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+4",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Warrior ring (i)#Nightmare_Zone": {
    "image_url": "https://oldschool.runescape.wiki/images/4/4c/Warrior_ring_%28i%29.png?b7686",
    "wiki_url": "https://oldschool.runescape.wiki/w/Warrior_ring_(i)#Nightmare_Zone",
    "stab_atk": "+0",
    "slash_atk": "+8",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+8",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Warrior ring (i)#Soul_Wars": {
    "image_url": "https://oldschool.runescape.wiki/images/4/4c/Warrior_ring_%28i%29.png?b7686",
    "wiki_url": "https://oldschool.runescape.wiki/w/Warrior_ring_(i)#Soul_Wars",
    "stab_atk": "+0",
    "slash_atk": "+8",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+8",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "Zenyte ring": {
    "image_url": "https://oldschool.runescape.wiki/images/b/b9/Zenyte_ring.png?37c64",
    "wiki_url": "https://oldschool.runescape.wiki/w/Zenyte_ring",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  },
  "'perfect' ring": {
    "image_url": "https://oldschool.runescape.wiki/images/0/00/%27perfect%27_ring.png?991ec",
    "wiki_url": "https://oldschool.runescape.wiki/w/%27perfect%27_ring",
    "stab_atk": "+0",
    "slash_atk": "+0",
    "crush_atk": "+0",
    "magic_atk": "+0",
    "ranged_atk": "+0",
    "stab_def": "+0",
    "slash_def": "+0",
    "crush_def": "+0",
    "magic_def": "+0",
    "ranged_def": "+0",
    "str_bonus": "+0",
    "ranged_str_bonus": "+0",
    "magic_str_bonus": "+0%",
    "prayer": "+0"
  }
}